package serverhandlers

import (
	"fmt"

	"github.com/opensvc/oc3/schema"
)

type propDef struct {
	Col     *schema.Col
	SQLExpr string
	Kind    string
}

func (p propDef) selectExpr() string {
	if p.SQLExpr != "" {
		return p.SQLExpr
	}
	if p.Col != nil {
		return p.Col.Qualified()
	}
	return ""
}

func col(c *schema.Col) propDef {
	return propDef{Col: c}
}

func colStr(c *schema.Col) propDef {
	return propDef{Col: c, SQLExpr: fmt.Sprintf("COALESCE(%s, '')", c.Qualified()), Kind: "string"}
}

func colInt(c *schema.Col) propDef {
	return propDef{Col: c, SQLExpr: fmt.Sprintf("COALESCE(%s, 0)", c.Qualified()), Kind: "int64"}
}

type JoinDef struct {
	MappingKey string
}

type propMapping struct {
	Available []string
	// Default is the subset of Available returned when no props are requested.
	// If nil, all Available props are returned by default.
	Default   []string
	Blacklist map[string]struct{}
	// Props maps prop names to their propDef (column reference + optional SQL override).
	// Enables column pushdown: only requested columns are fetched from DB.
	Props map[string]propDef
	// Joins declares joinable tables. A prop "table.column" is valid when "table"
	// is a key in Joins and "column" is listed in JoinDef.Columns.
	Joins map[string]JoinDef
}

var propsMapping = map[string]propMapping{
	"action_queue": {
		Available: []string{
			"id", "status", "command", "date_queued", "date_dequeued", "ret",
			"stdout", "stderr", "action_type", "user_id", "form_id", "connect_to",
			"node_id", "svc_id",
		},
		Props: map[string]propDef{
			"id":            col(schema.ActionQueueID),
			"status":        colStr(schema.ActionQueueStatus),
			"command":       colStr(schema.ActionQueueCommand),
			"date_queued":   colStr(schema.ActionQueueDateQueued),
			"date_dequeued": colStr(schema.ActionQueueDateDequeued),
			"ret":           colInt(schema.ActionQueueRet),
			"stdout":        colStr(schema.ActionQueueStdout),
			"stderr":        colStr(schema.ActionQueueStderr),
			"action_type":   colStr(schema.ActionQueueActionType),
			"user_id":       colInt(schema.ActionQueueUserID),
			"form_id":       colInt(schema.ActionQueueFormID),
			"connect_to":    colStr(schema.ActionQueueConnectTo),
			"node_id":       colStr(schema.ActionQueueNodeID),
			"svc_id":        colStr(schema.ActionQueueSvcID),
		},
	},
	"node": {
		Available: []string{
			"node_id", "nodename", "app", "node_env", "cluster_id",
			"loc_country", "loc_city", "loc_addr", "loc_building", "loc_floor", "loc_room", "loc_rack", "loc_zip",
			"cpu_freq", "cpu_cores", "cpu_dies", "cpu_vendor", "cpu_model", "cpu_threads",
			"mem_banks", "mem_slots", "mem_bytes",
			"os_name", "os_release", "os_update", "os_segment", "os_arch", "os_vendor", "os_kernel", "os_concat",
			"team_responsible", "team_integ", "team_support",
			"serial", "model", "manufacturer", "type", "assetname", "asset_env",
			"warranty_end", "maintenance_end",
			"status", "role", "sec_zone",
			"power_cabinet1", "power_cabinet2", "power_supply_nb", "power_protect", "power_protect_breaker", "power_breaker1", "power_breaker2",
			"blade_cabinet", "enclosure", "enclosureslot",
			"hv", "hvpool", "hvvdc",
			"fqdn", "connect_to", "listener_port", "version", "collector", "sp_version", "bios_version",
			"tz", "last_boot", "last_comm",
			"node_frozen", "node_frozen_at",
			"snooze_till", "notifications", "action_type",
			"hw_obs_warn_date", "hw_obs_alert_date", "os_obs_warn_date", "os_obs_alert_date",
			"updated",
		},
		Props: map[string]propDef{
			"node_id":               colStr(schema.NodesNodeID),
			"nodename":              colStr(schema.NodesNodename),
			"app":                   colStr(schema.NodesApp),
			"node_env":              colStr(schema.NodesNodeEnv),
			"cluster_id":            colStr(schema.NodesClusterID),
			"loc_country":           colStr(schema.NodesLocCountry),
			"loc_city":              colStr(schema.NodesLocCity),
			"loc_addr":              colStr(schema.NodesLocAddr),
			"loc_building":          colStr(schema.NodesLocBuilding),
			"loc_floor":             colStr(schema.NodesLocFloor),
			"loc_room":              colStr(schema.NodesLocRoom),
			"loc_rack":              colStr(schema.NodesLocRack),
			"loc_zip":               colStr(schema.NodesLocZip),
			"cpu_freq":              colStr(schema.NodesCPUFreq),
			"cpu_cores":             colInt(schema.NodesCPUCores),
			"cpu_dies":              colInt(schema.NodesCPUDies),
			"cpu_vendor":            colStr(schema.NodesCPUVendor),
			"cpu_model":             colStr(schema.NodesCPUModel),
			"cpu_threads":           colInt(schema.NodesCPUThreads),
			"mem_banks":             colInt(schema.NodesMEMBanks),
			"mem_slots":             colInt(schema.NodesMEMSlots),
			"mem_bytes":             colInt(schema.NodesMEMBytes),
			"os_name":               colStr(schema.NodesOSName),
			"os_release":            colStr(schema.NodesOSRelease),
			"os_update":             colStr(schema.NodesOSUpdate),
			"os_segment":            colStr(schema.NodesOSSegment),
			"os_arch":               colStr(schema.NodesOSArch),
			"os_vendor":             colStr(schema.NodesOSVendor),
			"os_kernel":             colStr(schema.NodesOSKernel),
			"os_concat":             colStr(schema.NodesOSConcat),
			"team_responsible":      colStr(schema.NodesTeamResponsible),
			"team_integ":            colStr(schema.NodesTeamInteg),
			"team_support":          colStr(schema.NodesTeamSupport),
			"serial":                colStr(schema.NodesSerial),
			"model":                 colStr(schema.NodesModel),
			"manufacturer":          colStr(schema.NodesManufacturer),
			"type":                  colStr(schema.NodesType),
			"assetname":             colStr(schema.NodesAssetname),
			"asset_env":             colStr(schema.NodesAssetEnv),
			"warranty_end":          colStr(schema.NodesWarrantyEnd),
			"maintenance_end":       colStr(schema.NodesMaintenanceEnd),
			"status":                colStr(schema.NodesStatus),
			"role":                  colStr(schema.NodesRole),
			"sec_zone":              colStr(schema.NodesSecZone),
			"power_cabinet1":        colStr(schema.NodesPowerCabinet1),
			"power_cabinet2":        colStr(schema.NodesPowerCabinet2),
			"power_supply_nb":       colInt(schema.NodesPowerSupplyNb),
			"power_protect":         colStr(schema.NodesPowerProtect),
			"power_protect_breaker": colStr(schema.NodesPowerProtectBreaker),
			"power_breaker1":        colStr(schema.NodesPowerBreaker1),
			"power_breaker2":        colStr(schema.NodesPowerBreaker2),
			"blade_cabinet":         colStr(schema.NodesBladeCabinet),
			"enclosure":             colStr(schema.NodesEnclosure),
			"enclosureslot":         colStr(schema.NodesEnclosureslot),
			"hv":                    colStr(schema.NodesHv),
			"hvpool":                colStr(schema.NodesHvpool),
			"hvvdc":                 colStr(schema.NodesHvvdc),
			"fqdn":                  colStr(schema.NodesFqdn),
			"connect_to":            colStr(schema.NodesConnectTo),
			"listener_port":         colInt(schema.NodesListenerPort),
			"version":               colStr(schema.NodesVersion),
			"collector":             colStr(schema.NodesCollector),
			"sp_version":            colStr(schema.NodesSpVersion),
			"bios_version":          colStr(schema.NodesBiosVersion),
			"tz":                    colStr(schema.NodesTz),
			"last_boot":             colStr(schema.NodesLastBoot),
			"last_comm":             colStr(schema.NodesLastComm),
			"node_frozen":           colStr(schema.NodesNodeFrozen),
			"node_frozen_at":        colStr(schema.NodesNodeFrozenAt),
			"snooze_till":           colStr(schema.NodesSnoozeTill),
			"notifications":         colStr(schema.NodesNotifications),
			"action_type":           colStr(schema.NodesActionType),
			"hw_obs_warn_date":      colStr(schema.NodesHWObsWarnDate),
			"hw_obs_alert_date":     colStr(schema.NodesHWObsAlertDate),
			"os_obs_warn_date":      colStr(schema.NodesOSObsWarnDate),
			"os_obs_alert_date":     colStr(schema.NodesOSObsAlertDate),
			"updated":               colStr(schema.NodesUpdated),
		},
	},
	"disk": {
		Available: []string{
			"disk_id", "disk_name", "disk_devid", "disk_vendor", "disk_model",
			"disk_size", "disk_used", "disk_alloc", "disk_raid", "disk_group",
			"disk_level", "disk_arrayid", "disk_dg", "disk_region",
			"node_id", "nodename", "svc_id", "svcname", "app", "updated",
		},
		Props: map[string]propDef{
			"disk_id":      col(schema.DiskinfoDiskID),
			"disk_name":    colStr(schema.DiskinfoDiskName),
			"disk_devid":   colStr(schema.DiskinfoDiskDevid),
			"disk_vendor":  colStr(schema.SvcdisksDiskVendor),
			"disk_model":   colStr(schema.SvcdisksDiskModel),
			"disk_size":    colInt(schema.DiskinfoDiskSize),
			"disk_used":    colInt(schema.SvcdisksDiskUsed),
			"disk_alloc":   colInt(schema.DiskinfoDiskAlloc),
			"disk_raid":    colStr(schema.DiskinfoDiskRaid),
			"disk_group":   colStr(schema.DiskinfoDiskGroup),
			"disk_level":   colInt(schema.DiskinfoDiskLevel),
			"disk_arrayid": colStr(schema.DiskinfoDiskArrayid),
			"disk_dg":      colStr(schema.SvcdisksDiskDG),
			"disk_region":  colStr(schema.SvcdisksDiskRegion),
			"node_id":      colStr(schema.SvcdisksNodeID),
			"nodename":     colStr(schema.NodesNodename),
			"svc_id":       colStr(schema.SvcdisksSvcID),
			"svcname":      colStr(schema.ServicesSvcname),
			"app":          colStr(schema.AppsApp),
			"updated":      colStr(schema.DiskinfoDiskUpdated),
		},
	},
	"disk_quota": {
		Available: []string{
			"array_name", "array_model", "dg_name",
			"dg_free", "dg_used", "dg_size", "dg_reserved", "dg_reservable",
			"app", "quota", "quota_used",
			"dg_id", "array_id", "app_id",
		},
		Props: map[string]propDef{
			"array_name":    {SQLExpr: "COALESCE(array_name, '') AS array_name", Kind: "string"},
			"array_model":   {SQLExpr: "COALESCE(array_model, '') AS array_model", Kind: "string"},
			"dg_name":       {SQLExpr: "COALESCE(dg_name, '') AS dg_name", Kind: "string"},
			"dg_free":       {SQLExpr: "COALESCE(dg_free, 0) AS dg_free", Kind: "int64"},
			"dg_used":       {SQLExpr: "COALESCE(dg_used, 0) AS dg_used", Kind: "int64"},
			"dg_size":       {SQLExpr: "COALESCE(dg_size, 0) AS dg_size", Kind: "int64"},
			"dg_reserved":   {SQLExpr: "COALESCE(dg_reserved, 0) AS dg_reserved", Kind: "int64"},
			"dg_reservable": {SQLExpr: "COALESCE(dg_reservable, 0) AS dg_reservable", Kind: "int64"},
			"app":           {SQLExpr: "COALESCE(app, '') AS app", Kind: "string"},
			"quota":         {SQLExpr: "COALESCE(quota, 0) AS quota", Kind: "int64"},
			"quota_used":    {SQLExpr: "COALESCE(quota_used, 0) AS quota_used", Kind: "int64"},
			"dg_id":         {SQLExpr: "COALESCE(dg_id, 0) AS dg_id", Kind: "int64"},
			"array_id":      {SQLExpr: "COALESCE(array_id, 0) AS array_id", Kind: "int64"},
			"app_id":        {SQLExpr: "COALESCE(app_id, 0) AS app_id", Kind: "int64"},
		},
	},
	"node_ip": {
		Available: []string{
			"id", "node_id", "nodename", "intf", "mac", "type", "addr", "mask", "updated", "flag_deprecated",
			"net_id", "net_name", "net_network", "net_netmask", "net_broadcast", "net_gateway",
			"net_begin", "net_end", "net_pvid", "net_prio", "net_comment", "net_team_responsible",
		},
		Default: []string{"node_id", "intf", "addr", "mask", "net_name", "net_network", "net_netmask", "net_gateway"},
		Props: map[string]propDef{
			"id":                   {SQLExpr: "id", Kind: "int64"},
			"node_id":              {SQLExpr: "COALESCE(node_id, '') AS node_id", Kind: "string"},
			"nodename":             {SQLExpr: "COALESCE(nodename, '') AS nodename", Kind: "string"},
			"intf":                 {SQLExpr: "COALESCE(intf, '') AS intf", Kind: "string"},
			"mac":                  {SQLExpr: "COALESCE(mac, '') AS mac", Kind: "string"},
			"type":                 {SQLExpr: "COALESCE(addr_type, '') AS type", Kind: "string"},
			"addr":                 {SQLExpr: "COALESCE(addr, '') AS addr", Kind: "string"},
			"mask":                 {SQLExpr: "COALESCE(mask, '') AS mask", Kind: "string"},
			"updated":              {SQLExpr: "COALESCE(addr_updated, '') AS updated", Kind: "string"},
			"flag_deprecated":      {SQLExpr: "COALESCE(flag_deprecated, 0) AS flag_deprecated", Kind: "int64"},
			"net_id":               {SQLExpr: "net_id", Kind: "int64"},
			"net_name":             {SQLExpr: "COALESCE(net_name, '') AS net_name", Kind: "string"},
			"net_network":          {SQLExpr: "COALESCE(net_network, '') AS net_network", Kind: "string"},
			"net_netmask":          {SQLExpr: "COALESCE(net_netmask, '') AS net_netmask", Kind: "string"},
			"net_broadcast":        {SQLExpr: "COALESCE(net_broadcast, '') AS net_broadcast", Kind: "string"},
			"net_gateway":          {SQLExpr: "COALESCE(net_gateway, '') AS net_gateway", Kind: "string"},
			"net_begin":            {SQLExpr: "COALESCE(net_begin, '') AS net_begin", Kind: "string"},
			"net_end":              {SQLExpr: "COALESCE(net_end, '') AS net_end", Kind: "string"},
			"net_pvid":             {SQLExpr: "COALESCE(net_pvid, '') AS net_pvid", Kind: "string"},
			"net_prio":             {SQLExpr: "COALESCE(prio, 0) AS net_prio", Kind: "int64"},
			"net_comment":          {SQLExpr: "COALESCE(net_comment, '') AS net_comment", Kind: "string"},
			"net_team_responsible": {SQLExpr: "COALESCE(net_team_responsible, '') AS net_team_responsible", Kind: "string"},
		},
	},
	"node_interface": {
		Available: []string{"id", "node_id", "intf", "mac", "type", "addr", "mask", "updated", "flag_deprecated"},
		Default:   []string{"id", "node_id", "intf", "mac", "updated", "flag_deprecated"},
		Blacklist: map[string]struct{}{"type": {}, "addr": {}, "mask": {}},
		Props: map[string]propDef{
			"id":              col(schema.NodeIPID),
			"node_id":         colStr(schema.NodeIPNodeID),
			"intf":            colStr(schema.NodeIPIntf),
			"mac":             colStr(schema.NodeIPMac),
			"type":            colStr(schema.NodeIPType),
			"addr":            colStr(schema.NodeIPAddr),
			"mask":            colStr(schema.NodeIPMask),
			"updated":         colStr(schema.NodeIPUpdated),
			"flag_deprecated": colInt(schema.NodeIPFlagDeprecated),
		},
		Joins: map[string]JoinDef{
			"nodes": {
				MappingKey: "node",
			},
		},
	},
	"node_hw": {
		Available: []string{"id", "node_id", "hw_type", "hw_path", "hw_class", "hw_description", "hw_driver", "updated"},
		Default:   []string{"node_id", "hw_type", "hw_path", "hw_class", "hw_description", "hw_driver", "updated"},
		Props: map[string]propDef{
			"id":             col(schema.NodeHWID),
			"node_id":        colStr(schema.NodeHWNodeID),
			"hw_type":        colStr(schema.NodeHWHWType),
			"hw_path":        colStr(schema.NodeHWHWPath),
			"hw_class":       colStr(schema.NodeHWHWClass),
			"hw_description": colStr(schema.NodeHWHWDescription),
			"hw_driver":      colStr(schema.NodeHWHWDriver),
			"updated":        colStr(schema.NodeHWUpdated),
		},
	},
	"hba": {
		Available: []string{"id", "node_id", "hba_id", "hba_type", "updated"},
		Props: map[string]propDef{
			"id":       col(schema.NodeHBAID),
			"node_id":  colStr(schema.NodeHBANodeID),
			"hba_id":   colStr(schema.NodeHBAHBAID),
			"hba_type": colStr(schema.NodeHBAHBAType),
			"updated":  colStr(schema.NodeHBAUpdated),
		},
	},
	"array": {
		Available: []string{
			"id", "array_name", "array_comment", "array_model",
			"array_firmware", "array_cache", "array_updated", "array_level",
		},
		Props: map[string]propDef{
			"id":             col(schema.StorArrayID),
			"array_name":     colStr(schema.StorArrayArrayName),
			"array_comment":  colStr(schema.StorArrayArrayComment),
			"array_model":    colStr(schema.StorArrayArrayModel),
			"array_firmware": colStr(schema.StorArrayArrayFirmware),
			"array_cache":    colInt(schema.StorArrayArrayCache),
			"array_updated":  colStr(schema.StorArrayArrayUpdated),
			"array_level":    colInt(schema.StorArrayArrayLevel),
		},
	},
	"app": {
		Available: []string{"id", "app", "updated", "app_domain", "app_team_ops", "description"},
		Props: map[string]propDef{
			"id":           col(schema.AppsID),
			"app":          col(schema.AppsApp),
			"updated":      colStr(schema.AppsUpdated),
			"app_domain":   colStr(schema.AppsAppDomain),
			"app_team_ops": colStr(schema.AppsAppTeamOps),
			"description":  colStr(schema.AppsDescription),
		},
	},
	"obsolescence": {
		Available: []string{
			"id", "obs_type", "obs_name", "obs_warn_date", "obs_alert_date",
			"obs_warn_date_updated_by", "obs_alert_date_updated_by",
			"obs_warn_date_updated", "obs_alert_date_updated", "obs_count",
		},
		Props: map[string]propDef{
			"id":                        {SQLExpr: "v_obsolescence.id", Kind: "int64"},
			"obs_type":                  {SQLExpr: "v_obsolescence.obs_type", Kind: "string"},
			"obs_name":                  {SQLExpr: "v_obsolescence.obs_name", Kind: "string"},
			"obs_warn_date":             {SQLExpr: "COALESCE(v_obsolescence.obs_warn_date, '')", Kind: "string"},
			"obs_alert_date":            {SQLExpr: "COALESCE(v_obsolescence.obs_alert_date, '')", Kind: "string"},
			"obs_warn_date_updated_by":  {SQLExpr: "v_obsolescence.obs_warn_date_updated_by", Kind: "string"},
			"obs_alert_date_updated_by": {SQLExpr: "v_obsolescence.obs_alert_date_updated_by", Kind: "string"},
			"obs_warn_date_updated":     {SQLExpr: "v_obsolescence.obs_warn_date_updated", Kind: "string"},
			"obs_alert_date_updated":    {SQLExpr: "v_obsolescence.obs_alert_date_updated", Kind: "string"},
			"obs_count":                 {SQLExpr: "v_obsolescence.obs_count", Kind: "int64"},
		},
	},
	"auth_group": {
		Available: []string{"id", "role", "privilege", "description"},
		Props: map[string]propDef{
			"id":          col(schema.AuthGroupID),
			"role":        colStr(schema.AuthGroupRole),
			"privilege":   colStr(schema.AuthGroupPrivilege),
			"description": colStr(schema.AuthGroupDescription),
		},
	},
	"user": {
		Available: []string{
			"id", "username", "email", "first_name", "last_name", "phone_work",
			"im_type", "im_username", "email_notifications", "im_notifications",
			"email_log_level", "im_log_level", "email_notifications_delay",
			"im_notifications_delay", "lock_filter", "registration_id",
			"reset_password_key", "quota_app", "quota_org_group", "quota_docker_registries",
		},
		Props: map[string]propDef{
			"id":                        col(schema.AuthUserID),
			"username":                  colStr(schema.AuthUserUsername),
			"email":                     colStr(schema.AuthUserEmail),
			"first_name":                colStr(schema.AuthUserFirstName),
			"last_name":                 colStr(schema.AuthUserLastName),
			"phone_work":                colStr(schema.AuthUserPhoneWork),
			"im_type":                   colStr(schema.AuthUserImType),
			"im_username":               colStr(schema.AuthUserImUsername),
			"email_notifications":       colStr(schema.AuthUserEmailNotifications),
			"im_notifications":          colStr(schema.AuthUserImNotifications),
			"email_log_level":           colStr(schema.AuthUserEmailLogLevel),
			"im_log_level":              colStr(schema.AuthUserImLogLevel),
			"email_notifications_delay": colStr(schema.AuthUserEmailNotificationsDelay),
			"im_notifications_delay":    colStr(schema.AuthUserImNotificationsDelay),
			"lock_filter":               colStr(schema.AuthUserLockFilter),
			"registration_id":           colStr(schema.AuthUserRegistrationID),
			"reset_password_key":        colStr(schema.AuthUserResetPasswordKey),
			"quota_app":                 colStr(schema.AuthUserQuotaApp),
			"quota_org_group":           colStr(schema.AuthUserQuotaOrgGroup),
			"quota_docker_registries":   colStr(schema.AuthUserQuotaDockerRegistries),
		},
	},
	"tag": {
		Available: []string{"id", "tag_name", "tag_created", "tag_exclude", "tag_data", "tag_id"},
		Blacklist: map[string]struct{}{"id": {}},
		Props: map[string]propDef{
			"id":          col(schema.TagsID),
			"tag_name":    colStr(schema.TagsTagName),
			"tag_created": colStr(schema.TagsTagCreated),
			"tag_exclude": colStr(schema.TagsTagExclude),
			"tag_data":    col(schema.TagsTagData),
			"tag_id":      colStr(schema.TagsTagID),
		},
	},
	"node_tag": {
		Available: []string{"id", "created", "node_id", "tag_id", "tag_attach_data"},
		Blacklist: map[string]struct{}{"id": {}},
		Props: map[string]propDef{
			"id":              col(schema.NodeTagsID),
			"created":         colStr(schema.NodeTagsCreated),
			"node_id":         colStr(schema.NodeTagsNodeID),
			"tag_id":          colStr(schema.NodeTagsTagID),
			"tag_attach_data": colStr(schema.NodeTagsTagAttachData),
		},
	},
	"svc_tag": {
		Available: []string{"id", "created", "svc_id", "tag_id", "tag_attach_data"},
		Blacklist: map[string]struct{}{"id": {}},
		Props: map[string]propDef{
			"id":              col(schema.SvcTagsID),
			"created":         colStr(schema.SvcTagsCreated),
			"svc_id":          colStr(schema.SvcTagsSvcID),
			"tag_id":          colStr(schema.SvcTagsTagID),
			"tag_attach_data": colStr(schema.SvcTagsTagAttachData),
		},
	},
	"service": {
		Available: []string{
			"id", "svc_id", "svcname", "cluster_id",
			"svc_status", "svc_availstatus",
			"svc_app", "svc_env", "svc_ha",
			"svc_topology", "svc_frozen", "svc_placement", "svc_provisioned",
			"svc_flex_min_nodes", "svc_flex_max_nodes", "svc_flex_target",
			"svc_flex_cpu_low_threshold", "svc_flex_cpu_high_threshold",
			"svc_autostart",
			"svc_nodes", "svc_drpnode", "svc_drpnodes", "svc_drptype",
			"svc_comment", "svc_created", "svc_status_updated",
			"svc_hostid", "svc_wave", "svc_config", "svc_config_updated",
			"svc_metrocluster", "svc_drnoaction",
			"svc_notifications", "svc_snooze_till",
			"updated",
		},
		Props: map[string]propDef{
			"id":                          col(schema.ServicesID),
			"svc_id":                      colStr(schema.ServicesSvcID),
			"svcname":                     colStr(schema.ServicesSvcname),
			"cluster_id":                  colStr(schema.ServicesClusterID),
			"svc_status":                  colStr(schema.ServicesSvcStatus),
			"svc_availstatus":             colStr(schema.ServicesSvcAvailstatus),
			"svc_app":                     colStr(schema.ServicesSvcApp),
			"svc_env":                     colStr(schema.ServicesSvcEnv),
			"svc_ha":                      colInt(schema.ServicesSvcHa),
			"svc_topology":                colStr(schema.ServicesSvcTopology),
			"svc_frozen":                  colStr(schema.ServicesSvcFrozen),
			"svc_placement":               colStr(schema.ServicesSvcPlacement),
			"svc_provisioned":             colStr(schema.ServicesSvcProvisioned),
			"svc_flex_min_nodes":          colInt(schema.ServicesSvcFlexMinNodes),
			"svc_flex_max_nodes":          colInt(schema.ServicesSvcFlexMaxNodes),
			"svc_flex_target":             colInt(schema.ServicesSvcFlexTarget),
			"svc_flex_cpu_low_threshold":  colInt(schema.ServicesSvcFlexCPULowThreshold),
			"svc_flex_cpu_high_threshold": colInt(schema.ServicesSvcFlexCPUHighThreshold),
			"svc_autostart":               colStr(schema.ServicesSvcAutostart),
			"svc_nodes":                   colStr(schema.ServicesSvcNodes),
			"svc_drpnode":                 colStr(schema.ServicesSvcDrpnode),
			"svc_drpnodes":                colStr(schema.ServicesSvcDrpnodes),
			"svc_drptype":                 colStr(schema.ServicesSvcDrptype),
			"svc_comment":                 colStr(schema.ServicesSvcComment),
			"svc_created":                 colStr(schema.ServicesSvcCreated),
			"svc_status_updated":          colStr(schema.ServicesSvcStatusUpdated),
			"svc_hostid":                  colStr(schema.ServicesSvcHostid),
			"svc_wave":                    colInt(schema.ServicesSvcWave),
			"svc_config":                  colStr(schema.ServicesSvcConfig),
			"svc_config_updated":          colStr(schema.ServicesSvcConfigUpdated),
			"svc_metrocluster":            colStr(schema.ServicesSvcMetrocluster),
			"svc_drnoaction":              colStr(schema.ServicesSvcDrnoaction),
			"svc_notifications":           colStr(schema.ServicesSvcNotifications),
			"svc_snooze_till":             colStr(schema.ServicesSvcSnoozeTill),
			"updated":                     colStr(schema.ServicesUpdated),
		},
	},
	"instance": {
		Available: []string{
			"svc_id", "node_id",
			"mon_svctype",
			"mon_availstatus", "mon_overallstatus",
			"mon_smon_status", "mon_smon_global_expect",
			"mon_ipstatus", "mon_fsstatus", "mon_diskstatus", "mon_containerstatus",
			"mon_sharestatus", "mon_syncstatus", "mon_appstatus", "mon_hbstatus",
			"mon_frozen", "mon_frozen_at", "mon_encap_frozen_at",
			"mon_vmname", "mon_vmtype", "mon_guestos", "mon_vcpus", "mon_vmem",
			"mon_updated", "mon_changed",
		},
		Default: []string{
			"svc_id", "node_id",
			"mon_availstatus", "mon_overallstatus", "mon_smon_status",
			"mon_frozen", "mon_updated",
		},
		Props: map[string]propDef{
			"svc_id":                 colStr(schema.SvcmonSvcID),
			"node_id":                colStr(schema.SvcmonNodeID),
			"mon_svctype":            colStr(schema.SvcmonMonSvctype),
			"mon_availstatus":        colStr(schema.SvcmonMonAvailstatus),
			"mon_overallstatus":      colStr(schema.SvcmonMonOverallstatus),
			"mon_smon_status":        colStr(schema.SvcmonMonSmonStatus),
			"mon_smon_global_expect": colStr(schema.SvcmonMonSmonGlobalExpect),
			"mon_ipstatus":           colStr(schema.SvcmonMonIpstatus),
			"mon_fsstatus":           colStr(schema.SvcmonMonFsstatus),
			"mon_diskstatus":         colStr(schema.SvcmonMonDiskstatus),
			"mon_containerstatus":    colStr(schema.SvcmonMonContainerstatus),
			"mon_sharestatus":        colStr(schema.SvcmonMonSharestatus),
			"mon_syncstatus":         colStr(schema.SvcmonMonSyncstatus),
			"mon_appstatus":          colStr(schema.SvcmonMonAppstatus),
			"mon_hbstatus":           colStr(schema.SvcmonMonHbstatus),
			"mon_frozen":             colStr(schema.SvcmonMonFrozen),
			"mon_frozen_at":          colStr(schema.SvcmonMonFrozenAt),
			"mon_encap_frozen_at":    colStr(schema.SvcmonMonEncapFrozenAt),
			"mon_vmname":             colStr(schema.SvcmonMonVmname),
			"mon_vmtype":             colStr(schema.SvcmonMonVmtype),
			"mon_guestos":            colStr(schema.SvcmonMonGuestos),
			"mon_vcpus":              colInt(schema.SvcmonMonVcpus),
			"mon_vmem":               colInt(schema.SvcmonMonVmem),
			"mon_updated":            colStr(schema.SvcmonMonUpdated),
			"mon_changed":            colStr(schema.SvcmonMonChanged),
		},
	},
	"instance_status_log": {
		Available: []string{
			"id",
			"svc_id", "node_id",
			"mon_begin", "mon_end",
			"mon_availstatus", "mon_overallstatus",
			"mon_ipstatus", "mon_fsstatus", "mon_diskstatus",
			"mon_sharestatus", "mon_containerstatus",
			"mon_syncstatus", "mon_hbstatus", "mon_appstatus",
		},
		Default: []string{
			"svc_id", "node_id",
			"mon_begin", "mon_end",
			"mon_availstatus", "mon_overallstatus",
		},
		Props: map[string]propDef{
			"id":                  col(schema.SvcmonLogID),
			"svc_id":              colStr(schema.SvcmonLogSvcID),
			"node_id":             colStr(schema.SvcmonLogNodeID),
			"mon_begin":           colStr(schema.SvcmonLogMonBegin),
			"mon_end":             colStr(schema.SvcmonLogMonEnd),
			"mon_availstatus":     colStr(schema.SvcmonLogMonAvailstatus),
			"mon_overallstatus":   colStr(schema.SvcmonLogMonOverallstatus),
			"mon_ipstatus":        colStr(schema.SvcmonLogMonIpstatus),
			"mon_fsstatus":        colStr(schema.SvcmonLogMonFsstatus),
			"mon_diskstatus":      colStr(schema.SvcmonLogMonDiskstatus),
			"mon_sharestatus":     colStr(schema.SvcmonLogMonSharestatus),
			"mon_containerstatus": colStr(schema.SvcmonLogMonContainerstatus),
			"mon_syncstatus":      colStr(schema.SvcmonLogMonSyncstatus),
			"mon_hbstatus":        colStr(schema.SvcmonLogMonHbstatus),
			"mon_appstatus":       colStr(schema.SvcmonLogMonAppstatus),
		},
	},
	"service_status_log": {
		Available: []string{
			"id", "svc_id", "svc_begin", "svc_end", "svc_availstatus",
		},
		Default: []string{
			"svc_id", "svc_begin", "svc_end", "svc_availstatus",
		},
		Props: map[string]propDef{
			"id":              col(schema.ServicesLogID),
			"svc_id":          colStr(schema.ServicesLogSvcID),
			"svc_begin":       colStr(schema.ServicesLogSvcBegin),
			"svc_end":         colStr(schema.ServicesLogSvcEnd),
			"svc_availstatus": colStr(schema.ServicesLogSvcAvailstatus),
		},
	},
	"moduleset": {
		Available: []string{"id", "modset_name", "modset_author", "modset_updated"},
		Props: map[string]propDef{
			"id":             col(schema.CompModulesetID),
			"modset_name":    colStr(schema.CompModulesetModsetName),
			"modset_author":  colStr(schema.CompModulesetModsetAuthor),
			"modset_updated": colStr(schema.CompModulesetModsetUpdated),
		},
	},
	"hidden_menu_entry": {
		Available: []string{"id", "group_id", "menu_entry"},
		Props: map[string]propDef{
			"id":         col(schema.GroupHiddenMenuEntriesID),
			"group_id":   colInt(schema.GroupHiddenMenuEntriesGroupID),
			"menu_entry": colStr(schema.GroupHiddenMenuEntriesMenuEntry),
		},
	},
	"ruleset": {
		Available: []string{"id", "ruleset_name", "ruleset_type", "ruleset_public"},
		Props: map[string]propDef{
			"id":             col(schema.CompRulesetsID),
			"ruleset_name":   colStr(schema.CompRulesetsRulesetName),
			"ruleset_type":   colStr(schema.CompRulesetsRulesetType),
			"ruleset_public": colStr(schema.CompRulesetsRulesetPublic),
		},
	},
	"alert_event": {
		Available: []string{"id", "svc_id", "node_id", "dash_begin", "dash_end", "dash_md5"},
		Props: map[string]propDef{
			"id":         col(schema.DashboardEventsID),
			"svc_id":     colStr(schema.DashboardEventsSvcID),
			"node_id":    colStr(schema.DashboardEventsNodeID),
			"dash_begin": colStr(schema.DashboardEventsDashBegin),
			"dash_end":   colStr(schema.DashboardEventsDashEnd),
			"dash_md5":   colStr(schema.DashboardEventsDashMD5),
		},
	},
	"alert": {
		Available: []string{
			"id", "dash_type", "svc_id", "node_id",
			"dash_severity", "dash_fmt", "dash_dict",
			"dash_created", "dash_updated",
			"dash_md5", "dash_dict_md5", "dash_env", "dash_instance",
			"alert",
		},
		Default: []string{
			"id", "dash_type", "svc_id", "node_id",
			"dash_severity",
			"dash_created", "dash_updated",
			"dash_env", "dash_instance",
			"alert",
		},
		Props: map[string]propDef{
			"id":            col(schema.DashboardID),
			"dash_type":     colStr(schema.DashboardDashType),
			"svc_id":        colStr(schema.DashboardSvcID),
			"node_id":       colStr(schema.DashboardNodeID),
			"dash_severity": colInt(schema.DashboardDashSeverity),
			"dash_fmt":      colStr(schema.DashboardDashFmt),
			"dash_dict":     colStr(schema.DashboardDashDict),
			"dash_created":  colStr(schema.DashboardDashCreated),
			"dash_updated":  colStr(schema.DashboardDashUpdated),
			"dash_md5":      colStr(schema.DashboardDashMD5),
			"dash_dict_md5": colStr(schema.DashboardDashDictMD5),
			"dash_env":      colStr(schema.DashboardDashEnv),
			"dash_instance": colStr(schema.DashboardDashInstance),
		},
		// A dashboard entry points at a node or a service by id only. The names live
		// in the joined tables, as in the historical collector's own alert query.
		Joins: map[string]JoinDef{
			"nodes":    {MappingKey: "node"},
			"services": {MappingKey: "service"},
		},
	},
	"check": {
		Available: []string{
			"id", "node_id", "svc_id",
			"chk_type", "chk_instance",
			"chk_value", "chk_low", "chk_high", "chk_err",
			"chk_threshold_provider",
			"chk_created", "chk_updated",
		},
		Props: map[string]propDef{
			"id":                     col(schema.ChecksLiveID),
			"node_id":                colStr(schema.ChecksLiveNodeID),
			"svc_id":                 colStr(schema.ChecksLiveSvcID),
			"chk_type":               colStr(schema.ChecksLiveChkType),
			"chk_instance":           colStr(schema.ChecksLiveChkInstance),
			"chk_value":              colInt(schema.ChecksLiveChkValue),
			"chk_low":                colInt(schema.ChecksLiveChkLow),
			"chk_high":               colInt(schema.ChecksLiveChkHigh),
			"chk_err":                colInt(schema.ChecksLiveChkErr),
			"chk_threshold_provider": colStr(schema.ChecksLiveChkThresholdProvider),
			"chk_created":            colStr(schema.ChecksLiveChkCreated),
			"chk_updated":            colStr(schema.ChecksLiveChkUpdated),
		},
	},
	"resource": {
		Available: []string{
			"id", "svc_id", "node_id", "rid", "res_status",
			"res_type", "res_desc", "res_log",
			"res_monitor", "res_disable", "res_optional",
			"vmname", "changed", "updated",
		},
		Default: []string{
			"svc_id", "node_id", "rid", "res_status",
			"res_type", "res_monitor", "res_disable", "res_optional",
			"updated",
		},
		Props: map[string]propDef{
			"id":           col(schema.ResmonID),
			"svc_id":       colStr(schema.ResmonSvcID),
			"node_id":      colStr(schema.ResmonNodeID),
			"rid":          colStr(schema.ResmonRid),
			"res_status":   colStr(schema.ResmonResStatus),
			"res_type":     colStr(schema.ResmonResType),
			"res_desc":     colStr(schema.ResmonResDesc),
			"res_log":      colStr(schema.ResmonResLog),
			"res_monitor":  colStr(schema.ResmonResMonitor),
			"res_disable":  colStr(schema.ResmonResDisable),
			"res_optional": colStr(schema.ResmonResOptional),
			"vmname":       colStr(schema.ResmonVmname),
			"changed":      colStr(schema.ResmonChanged),
			"updated":      colStr(schema.ResmonUpdated),
		},
	},
	"resource_log": {
		Available: []string{
			"id", "svc_id", "node_id", "rid", "res_status",
			"res_begin", "res_end", "res_log",
		},
		Default: []string{
			"svc_id", "node_id", "rid", "res_status",
			"res_begin", "res_end",
		},
		Props: map[string]propDef{
			"id":         {SQLExpr: "id", Kind: "int64"},
			"svc_id":     {SQLExpr: "COALESCE(svc_id, '') AS svc_id", Kind: "string"},
			"node_id":    {SQLExpr: "COALESCE(node_id, '') AS node_id", Kind: "string"},
			"rid":        {SQLExpr: "COALESCE(rid, '') AS rid", Kind: "string"},
			"res_status": {SQLExpr: "COALESCE(res_status, '') AS res_status", Kind: "string"},
			"res_begin":  {SQLExpr: "COALESCE(res_begin, '') AS res_begin", Kind: "string"},
			"res_end":    {SQLExpr: "COALESCE(res_end, '') AS res_end", Kind: "string"},
			"res_log":    {SQLExpr: "COALESCE(res_log, '') AS res_log", Kind: "string"},
		},
	},
	"resinfo": {
		Available: []string{"id", "rid", "res_key", "res_value", "updated", "topology", "node_id", "svc_id"},
		Props: map[string]propDef{
			"id":        col(schema.ResinfoID),
			"rid":       colStr(schema.ResinfoRid),
			"res_key":   colStr(schema.ResinfoResKey),
			"res_value": colStr(schema.ResinfoResValue),
			"updated":   colStr(schema.ResinfoUpdated),
			"topology":  colStr(schema.ResinfoTopology),
			"node_id":   colStr(schema.ResinfoNodeID),
			"svc_id":    colStr(schema.ResinfoSvcID),
		},
	},
	"comp_status": {
		Available: []string{"id", "run_module", "node_id", "svc_id", "run_status", "run_log", "run_date", "run_action", "rset_md5"},
		Default:   []string{"id", "run_module", "run_status", "run_date", "run_action", "svc_id"},
		Props: map[string]propDef{
			"id":         col(schema.CompStatusID),
			"run_module": colStr(schema.CompStatusRunModule),
			"node_id":    colStr(schema.CompStatusNodeID),
			"svc_id":     colStr(schema.CompStatusSvcID),
			"run_status": colInt(schema.CompStatusRunStatus),
			"run_log":    colStr(schema.CompStatusRunLog),
			"run_date":   colStr(schema.CompStatusRunDate),
			"run_action": colStr(schema.CompStatusRunAction),
			"rset_md5":   colStr(schema.CompStatusRsetMD5),
		},
	},
	"filter": {
		Available: []string{
			"id", "f_table", "f_field", "f_value", "f_op",
			"f_updated", "f_author", "f_cksum", "f_label",
		},
		Props: map[string]propDef{
			"id":        col(schema.GenFiltersID),
			"f_table":   colStr(schema.GenFiltersFTable),
			"f_field":   colStr(schema.GenFiltersFField),
			"f_value":   colStr(schema.GenFiltersFValue),
			"f_op":      colStr(schema.GenFiltersFOp),
			"f_updated": colStr(schema.GenFiltersFUpdated),
			"f_author":  colStr(schema.GenFiltersFAuthor),
			"f_cksum":   colStr(schema.GenFiltersFCksum),
			"f_label":   colStr(schema.GenFiltersFLabel),
		},
	},
	"filterset": {
		Available: []string{
			"id", "fset_name", "fset_updated", "fset_author", "fset_stats",
		},
		Props: map[string]propDef{
			"id":           col(schema.GenFiltersetsID),
			"fset_name":    colStr(schema.GenFiltersetsFsetName),
			"fset_updated": colStr(schema.GenFiltersetsFsetUpdated),
			"fset_author":  colStr(schema.GenFiltersetsFsetAuthor),
			"fset_stats":   colStr(schema.GenFiltersetsFsetStats),
		},
	},
	"filterset_filter": {
		Available: []string{
			"id", "f_table", "f_field", "f_value", "f_op",
			"f_updated", "f_author", "f_cksum", "f_label",
			"f_log_op", "f_order", "fset_id", "encap_fset_id", "join_id",
		},
		Props: map[string]propDef{
			"id":            col(schema.GenFiltersID),
			"f_table":       colStr(schema.GenFiltersFTable),
			"f_field":       colStr(schema.GenFiltersFField),
			"f_value":       colStr(schema.GenFiltersFValue),
			"f_op":          colStr(schema.GenFiltersFOp),
			"f_updated":     colStr(schema.GenFiltersFUpdated),
			"f_author":      colStr(schema.GenFiltersFAuthor),
			"f_cksum":       colStr(schema.GenFiltersFCksum),
			"f_label":       colStr(schema.GenFiltersFLabel),
			"f_log_op":      colStr(schema.GenFiltersetsFiltersFLogOp),
			"f_order":       colInt(schema.GenFiltersetsFiltersFOrder),
			"fset_id":       col(schema.GenFiltersetsFiltersFsetID),
			"encap_fset_id": colInt(schema.GenFiltersetsFiltersEncapFsetID),
			"join_id":       {SQLExpr: "gen_filtersets_filters.id AS join_id", Kind: "int64"},
		},
	},
	"comp_log": {
		Available: []string{
			"id", "run_module", "run_status", "run_log",
			"run_date", "run_action", "rset_md5",
			"node_id", "svc_id",
		},
		Default: []string{
			"id", "run_module", "run_status", "run_date", "run_action",
			"node_id", "svc_id",
		},
		Props: map[string]propDef{
			"id":         col(schema.CompLogID),
			"run_module": colStr(schema.CompLogRunModule),
			"run_status": colInt(schema.CompLogRunStatus),
			"run_log":    colStr(schema.CompLogRunLog),
			"run_date":   colStr(schema.CompLogRunDate),
			"run_action": colStr(schema.CompLogRunAction),
			"rset_md5":   colStr(schema.CompLogRsetMD5),
			"node_id":    colStr(schema.CompLogNodeID),
			"svc_id":     colStr(schema.CompLogSvcID),
		},
	},
	"log_event": {
		Available: []string{
			"id", "log_action", "log_user", "log_fmt", "log_dict", "log_date",
			"svc_id", "node_id", "log_level", "log_entry_id",
			"log_gtalk_sent", "log_email_sent",
		},
		Default: []string{
			"id", "log_action", "log_user", "log_fmt", "log_date",
			"svc_id", "node_id", "log_level",
		},
		Props: map[string]propDef{
			"id":             col(schema.LogID),
			"log_action":     colStr(schema.LogLogAction),
			"log_user":       colStr(schema.LogLogUser),
			"log_fmt":        colStr(schema.LogLogFmt),
			"log_dict":       colStr(schema.LogLogDict),
			"log_date":       colStr(schema.LogLogDate),
			"svc_id":         colStr(schema.LogSvcID),
			"node_id":        colStr(schema.LogNodeID),
			"log_level":      colStr(schema.LogLogLevel),
			"log_entry_id":   colInt(schema.LogLogEntryID),
			"log_gtalk_sent": colInt(schema.LogLogGtalkSent),
			"log_email_sent": colInt(schema.LogLogEmailSent),
		},
	},
}
