// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package server

import (
	"encoding/json"

	"github.com/oapi-codegen/runtime"
)

const (
	BasicAuthScopes  = "basicAuth.Scopes"
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for PostNodesJSONBodyActionType.
const (
	PostNodesJSONBodyActionTypePull PostNodesJSONBodyActionType = "pull"
	PostNodesJSONBodyActionTypePush PostNodesJSONBodyActionType = "push"
)

// Defines values for PostNodeJSONBodyActionType.
const (
	PostNodeJSONBodyActionTypePull PostNodeJSONBodyActionType = "pull"
	PostNodeJSONBodyActionTypePush PostNodeJSONBodyActionType = "push"
)

// ListMeta defines model for ListMeta.
type ListMeta struct {
	AvailableProps *[]string       `json:"available_props,omitempty"`
	Count          *int            `json:"count,omitempty"`
	Distinct       *map[string]int `json:"distinct,omitempty"`
	IncludedProps  *[]string       `json:"included_props,omitempty"`
	Limit          *int            `json:"limit,omitempty"`
	Offset         *int            `json:"offset,omitempty"`
	Total          *int            `json:"total,omitempty"`
}

// ListResponse defines model for ListResponse.
type ListResponse struct {
	Data ListResponse_Data `json:"data"`
	Meta *ListMeta         `json:"meta,omitempty"`
}

// ListResponseData0 defines model for .
type ListResponseData0 = []map[string]interface{}

// ListResponseData1 defines model for .
type ListResponseData1 map[string]map[string]int

// ListResponse_Data defines model for ListResponse.Data.
type ListResponse_Data struct {
	union json.RawMessage
}

// Problem defines model for Problem.
type Problem struct {
	// Text A human-readable explanation specific to this occurrence of the
	// problem.
	Text string `json:"text"`
}

// Version defines model for version.
type Version struct {
	Version string `json:"version"`
}

// InPathMsetId defines model for inPathMsetId.
type InPathMsetId = string

// InPathNodeId defines model for inPathNodeId.
type InPathNodeId = string

// InPathRsetId defines model for inPathRsetId.
type InPathRsetId = string

// InQueryGroupby defines model for inQueryGroupby.
type InQueryGroupby = string

// InQueryLimit defines model for inQueryLimit.
type InQueryLimit = int

// InQueryMeta defines model for inQueryMeta.
type InQueryMeta = string

// InQueryOffset defines model for inQueryOffset.
type InQueryOffset = int

// InQueryOrderby defines model for inQueryOrderby.
type InQueryOrderby = string

// InQueryProps defines model for inQueryProps.
type InQueryProps = string

// InQueryStats defines model for inQueryStats.
type InQueryStats = string

// N400 defines model for 400.
type N400 = Problem

// N401 defines model for 401.
type N401 = Problem

// N403 defines model for 403.
type N403 = Problem

// N404 defines model for 404.
type N404 = Problem

// N409 defines model for 409.
type N409 = Problem

// N500 defines model for 500.
type N500 = Problem

// GetAppsParams defines parameters for GetApps.
type GetAppsParams struct {
	// Props A list of properties to include in each data dictionnary.
	Props *InQueryProps `form:"props,omitempty" json:"props,omitempty"`

	// Limit The maximum number of entries to return. 0 means no limit.
	Limit *InQueryLimit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Skip the first entries of the data cursor.
	Offset *InQueryOffset `form:"offset,omitempty" json:"offset,omitempty"`

	// Meta Include metadata in the response. Enabled by default. Use false or 0 to omit the meta field.
	Meta *InQueryMeta `form:"meta,omitempty" json:"meta,omitempty"`

	// Stats Controls the inclusion in the returned dictionnary of a "stats" key, containing the selected properties distinct values counts.
	Stats *InQueryStats `form:"stats,omitempty" json:"stats,omitempty"`

	// Orderby Comma-separated list of properties to sort by. Prefix a property with - for descending order (e.g. orderby=nodename,-app).
	Orderby *InQueryOrderby `form:"orderby,omitempty" json:"orderby,omitempty"`

	// Groupby Comma-separated list of properties to group the result by (e.g. groupby=app,svcname).
	Groupby *InQueryGroupby `form:"groupby,omitempty" json:"groupby,omitempty"`
}

// PostAppsJSONBody defines parameters for PostApps.
type PostAppsJSONBody struct {
	App         string  `json:"app"`
	AppDomain   *string `json:"app_domain,omitempty"`
	AppTeamOps  *string `json:"app_team_ops,omitempty"`
	Description *string `json:"description,omitempty"`
}

// GetAppParams defines parameters for GetApp.
type GetAppParams struct {
	// Props A list of properties to include in each data dictionnary.
	Props *InQueryProps `form:"props,omitempty" json:"props,omitempty"`
}

// PostAppJSONBody defines parameters for PostApp.
type PostAppJSONBody struct {
	App         *string `json:"app,omitempty"`
	AppDomain   *string `json:"app_domain,omitempty"`
	AppTeamOps  *string `json:"app_team_ops,omitempty"`
	Description *string `json:"description,omitempty"`
}

// GetAppPublicationsParams defines parameters for GetAppPublications.
type GetAppPublicationsParams struct {
	// Props A list of properties to include in each data dictionnary.
	Props *InQueryProps `form:"props,omitempty" json:"props,omitempty"`

	// Limit The maximum number of entries to return. 0 means no limit.
	Limit *InQueryLimit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Skip the first entries of the data cursor.
	Offset *InQueryOffset `form:"offset,omitempty" json:"offset,omitempty"`

	// Meta Include metadata in the response. Enabled by default. Use false or 0 to omit the meta field.
	Meta *InQueryMeta `form:"meta,omitempty" json:"meta,omitempty"`

	// Stats Controls the inclusion in the returned dictionnary of a "stats" key, containing the selected properties distinct values counts.
	Stats *InQueryStats `form:"stats,omitempty" json:"stats,omitempty"`

	// Orderby Comma-separated list of properties to sort by. Prefix a property with - for descending order (e.g. orderby=nodename,-app).
	Orderby *InQueryOrderby `form:"orderby,omitempty" json:"orderby,omitempty"`

	// Groupby Comma-separated list of properties to group the result by (e.g. groupby=app,svcname).
	Groupby *InQueryGroupby `form:"groupby,omitempty" json:"groupby,omitempty"`
}

// GetAppResponsiblesParams defines parameters for GetAppResponsibles.
type GetAppResponsiblesParams struct {
	// Props A list of properties to include in each data dictionnary.
	Props *InQueryProps `form:"props,omitempty" json:"props,omitempty"`

	// Limit The maximum number of entries to return. 0 means no limit.
	Limit *InQueryLimit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Skip the first entries of the data cursor.
	Offset *InQueryOffset `form:"offset,omitempty" json:"offset,omitempty"`

	// Meta Include metadata in the response. Enabled by default. Use false or 0 to omit the meta field.
	Meta *InQueryMeta `form:"meta,omitempty" json:"meta,omitempty"`

	// Stats Controls the inclusion in the returned dictionnary of a "stats" key, containing the selected properties distinct values counts.
	Stats *InQueryStats `form:"stats,omitempty" json:"stats,omitempty"`

	// Orderby Comma-separated list of properties to sort by. Prefix a property with - for descending order (e.g. orderby=nodename,-app).
	Orderby *InQueryOrderby `form:"orderby,omitempty" json:"orderby,omitempty"`

	// Groupby Comma-separated list of properties to group the result by (e.g. groupby=app,svcname).
	Groupby *InQueryGroupby `form:"groupby,omitempty" json:"groupby,omitempty"`
}

// GetArraysParams defines parameters for GetArrays.
type GetArraysParams struct {
	// Props A list of properties to include in each data dictionnary.
	Props *InQueryProps `form:"props,omitempty" json:"props,omitempty"`

	// Limit The maximum number of entries to return. 0 means no limit.
	Limit *InQueryLimit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Skip the first entries of the data cursor.
	Offset *InQueryOffset `form:"offset,omitempty" json:"offset,omitempty"`

	// Meta Include metadata in the response. Enabled by default. Use false or 0 to omit the meta field.
	Meta *InQueryMeta `form:"meta,omitempty" json:"meta,omitempty"`

	// Stats Controls the inclusion in the returned dictionnary of a "stats" key, containing the selected properties distinct values counts.
	Stats *InQueryStats `form:"stats,omitempty" json:"stats,omitempty"`

	// Orderby Comma-separated list of properties to sort by. Prefix a property with - for descending order (e.g. orderby=nodename,-app).
	Orderby *InQueryOrderby `form:"orderby,omitempty" json:"orderby,omitempty"`

	// Groupby Comma-separated list of properties to group the result by (e.g. groupby=app,svcname).
	Groupby *InQueryGroupby `form:"groupby,omitempty" json:"groupby,omitempty"`
}

// PostAuthNodeJSONBody defines parameters for PostAuthNode.
type PostAuthNodeJSONBody struct {
	App      *string `json:"app,omitempty"`
	Nodename string  `json:"nodename"`
}

// GetDisksParams defines parameters for GetDisks.
type GetDisksParams struct {
	// Props A list of properties to include in each data dictionnary.
	Props *InQueryProps `form:"props,omitempty" json:"props,omitempty"`

	// Limit The maximum number of entries to return. 0 means no limit.
	Limit *InQueryLimit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Skip the first entries of the data cursor.
	Offset *InQueryOffset `form:"offset,omitempty" json:"offset,omitempty"`

	// Meta Include metadata in the response. Enabled by default. Use false or 0 to omit the meta field.
	Meta *InQueryMeta `form:"meta,omitempty" json:"meta,omitempty"`

	// Stats Controls the inclusion in the returned dictionnary of a "stats" key, containing the selected properties distinct values counts.
	Stats *InQueryStats `form:"stats,omitempty" json:"stats,omitempty"`

	// Orderby Comma-separated list of properties to sort by. Prefix a property with - for descending order (e.g. orderby=nodename,-app).
	Orderby *InQueryOrderby `form:"orderby,omitempty" json:"orderby,omitempty"`

	// Groupby Comma-separated list of properties to group the result by (e.g. groupby=app,svcname).
	Groupby *InQueryGroupby `form:"groupby,omitempty" json:"groupby,omitempty"`
}

// GetDiskParams defines parameters for GetDisk.
type GetDiskParams struct {
	// Props A list of properties to include in each data dictionnary.
	Props *InQueryProps `form:"props,omitempty" json:"props,omitempty"`

	// Limit The maximum number of entries to return. 0 means no limit.
	Limit *InQueryLimit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Skip the first entries of the data cursor.
	Offset *InQueryOffset `form:"offset,omitempty" json:"offset,omitempty"`

	// Meta Include metadata in the response. Enabled by default. Use false or 0 to omit the meta field.
	Meta *InQueryMeta `form:"meta,omitempty" json:"meta,omitempty"`

	// Stats Controls the inclusion in the returned dictionnary of a "stats" key, containing the selected properties distinct values counts.
	Stats *InQueryStats `form:"stats,omitempty" json:"stats,omitempty"`

	// Orderby Comma-separated list of properties to sort by. Prefix a property with - for descending order (e.g. orderby=nodename,-app).
	Orderby *InQueryOrderby `form:"orderby,omitempty" json:"orderby,omitempty"`

	// Groupby Comma-separated list of properties to group the result by (e.g. groupby=app,svcname).
	Groupby *InQueryGroupby `form:"groupby,omitempty" json:"groupby,omitempty"`
}

// GetNodesParams defines parameters for GetNodes.
type GetNodesParams struct {
	// Props A list of properties to include in each data dictionnary.
	Props *InQueryProps `form:"props,omitempty" json:"props,omitempty"`

	// Limit The maximum number of entries to return. 0 means no limit.
	Limit *InQueryLimit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Skip the first entries of the data cursor.
	Offset *InQueryOffset `form:"offset,omitempty" json:"offset,omitempty"`

	// Meta Include metadata in the response. Enabled by default. Use false or 0 to omit the meta field.
	Meta *InQueryMeta `form:"meta,omitempty" json:"meta,omitempty"`

	// Stats Controls the inclusion in the returned dictionnary of a "stats" key, containing the selected properties distinct values counts.
	Stats *InQueryStats `form:"stats,omitempty" json:"stats,omitempty"`

	// Orderby Comma-separated list of properties to sort by. Prefix a property with - for descending order (e.g. orderby=nodename,-app).
	Orderby *InQueryOrderby `form:"orderby,omitempty" json:"orderby,omitempty"`

	// Groupby Comma-separated list of properties to group the result by (e.g. groupby=app,svcname).
	Groupby *InQueryGroupby `form:"groupby,omitempty" json:"groupby,omitempty"`
}

// PostNodesJSONBody defines parameters for PostNodes.
type PostNodesJSONBody struct {
	ActionType          *PostNodesJSONBodyActionType `json:"action_type,omitempty"`
	App                 *string                      `json:"app,omitempty"`
	AssetEnv            *string                      `json:"asset_env,omitempty"`
	Assetname           *string                      `json:"assetname,omitempty"`
	BiosVersion         *string                      `json:"bios_version,omitempty"`
	ClusterId           *string                      `json:"cluster_id,omitempty"`
	Collector           *string                      `json:"collector,omitempty"`
	ConnectTo           *string                      `json:"connect_to,omitempty"`
	CpuCores            *int                         `json:"cpu_cores,omitempty"`
	CpuDies             *int                         `json:"cpu_dies,omitempty"`
	CpuFreq             *string                      `json:"cpu_freq,omitempty"`
	CpuModel            *string                      `json:"cpu_model,omitempty"`
	CpuThreads          *int                         `json:"cpu_threads,omitempty"`
	CpuVendor           *string                      `json:"cpu_vendor,omitempty"`
	Enclosure           *string                      `json:"enclosure,omitempty"`
	Enclosureslot       *string                      `json:"enclosureslot,omitempty"`
	Fqdn                *string                      `json:"fqdn,omitempty"`
	Hv                  *string                      `json:"hv,omitempty"`
	Hvpool              *string                      `json:"hvpool,omitempty"`
	Hvvdc               *string                      `json:"hvvdc,omitempty"`
	HwObsAlertDate      *string                      `json:"hw_obs_alert_date,omitempty"`
	HwObsWarnDate       *string                      `json:"hw_obs_warn_date,omitempty"`
	LastBoot            *string                      `json:"last_boot,omitempty"`
	LastComm            *string                      `json:"last_comm,omitempty"`
	ListenerPort        *int                         `json:"listener_port,omitempty"`
	LocAddr             *string                      `json:"loc_addr,omitempty"`
	LocBuilding         *string                      `json:"loc_building,omitempty"`
	LocCity             *string                      `json:"loc_city,omitempty"`
	LocCountry          *string                      `json:"loc_country,omitempty"`
	LocFloor            *string                      `json:"loc_floor,omitempty"`
	LocRack             *string                      `json:"loc_rack,omitempty"`
	LocRoom             *string                      `json:"loc_room,omitempty"`
	LocZip              *string                      `json:"loc_zip,omitempty"`
	MaintenanceEnd      *string                      `json:"maintenance_end,omitempty"`
	Manufacturer        *string                      `json:"manufacturer,omitempty"`
	MemBanks            *int                         `json:"mem_banks,omitempty"`
	MemBytes            *int                         `json:"mem_bytes,omitempty"`
	MemSlots            *int                         `json:"mem_slots,omitempty"`
	Model               *string                      `json:"model,omitempty"`
	NodeEnv             *string                      `json:"node_env,omitempty"`
	NodeFrozen          *bool                        `json:"node_frozen,omitempty"`
	NodeFrozenAt        *string                      `json:"node_frozen_at,omitempty"`
	NodeId              *string                      `json:"node_id,omitempty"`
	Nodename            *string                      `json:"nodename,omitempty"`
	Notifications       *bool                        `json:"notifications,omitempty"`
	OsArch              *string                      `json:"os_arch,omitempty"`
	OsConcat            *string                      `json:"os_concat,omitempty"`
	OsKernel            *string                      `json:"os_kernel,omitempty"`
	OsName              *string                      `json:"os_name,omitempty"`
	OsObsAlertDate      *string                      `json:"os_obs_alert_date,omitempty"`
	OsObsWarnDate       *string                      `json:"os_obs_warn_date,omitempty"`
	OsRelease           *string                      `json:"os_release,omitempty"`
	OsVendor            *string                      `json:"os_vendor,omitempty"`
	PowerBreaker1       *string                      `json:"power_breaker1,omitempty"`
	PowerBreaker2       *string                      `json:"power_breaker2,omitempty"`
	PowerCabinet1       *string                      `json:"power_cabinet1,omitempty"`
	PowerCabinet2       *string                      `json:"power_cabinet2,omitempty"`
	PowerProtect        *string                      `json:"power_protect,omitempty"`
	PowerProtectBreaker *string                      `json:"power_protect_breaker,omitempty"`
	PowerSupplyNb       *int                         `json:"power_supply_nb,omitempty"`
	Role                *string                      `json:"role,omitempty"`
	SecZone             *string                      `json:"sec_zone,omitempty"`
	Serial              *string                      `json:"serial,omitempty"`
	SnoozeTill          *string                      `json:"snooze_till,omitempty"`
	SpVersion           *string                      `json:"sp_version,omitempty"`
	Status              *string                      `json:"status,omitempty"`
	TeamInteg           *string                      `json:"team_integ,omitempty"`
	TeamResponsible     *string                      `json:"team_responsible,omitempty"`
	TeamSupport         *string                      `json:"team_support,omitempty"`
	Type                *string                      `json:"type,omitempty"`
	Tz                  *string                      `json:"tz,omitempty"`
	Updated             *string                      `json:"updated,omitempty"`
	Version             *string                      `json:"version,omitempty"`
	WarrantyEnd         *string                      `json:"warranty_end,omitempty"`
}

// PostNodesJSONBodyActionType defines parameters for PostNodes.
type PostNodesJSONBodyActionType string

// GetNodesHardwareParams defines parameters for GetNodesHardware.
type GetNodesHardwareParams struct {
	// Props A list of properties to include in each data dictionnary.
	Props *InQueryProps `form:"props,omitempty" json:"props,omitempty"`

	// Limit The maximum number of entries to return. 0 means no limit.
	Limit *InQueryLimit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Skip the first entries of the data cursor.
	Offset *InQueryOffset `form:"offset,omitempty" json:"offset,omitempty"`

	// Meta Include metadata in the response. Enabled by default. Use false or 0 to omit the meta field.
	Meta *InQueryMeta `form:"meta,omitempty" json:"meta,omitempty"`

	// Stats Controls the inclusion in the returned dictionnary of a "stats" key, containing the selected properties distinct values counts.
	Stats *InQueryStats `form:"stats,omitempty" json:"stats,omitempty"`

	// Orderby Comma-separated list of properties to sort by. Prefix a property with - for descending order (e.g. orderby=nodename,-app).
	Orderby *InQueryOrderby `form:"orderby,omitempty" json:"orderby,omitempty"`

	// Groupby Comma-separated list of properties to group the result by (e.g. groupby=app,svcname).
	Groupby *InQueryGroupby `form:"groupby,omitempty" json:"groupby,omitempty"`
}

// GetNodesHbasParams defines parameters for GetNodesHbas.
type GetNodesHbasParams struct {
	// Props A list of properties to include in each data dictionnary.
	Props *InQueryProps `form:"props,omitempty" json:"props,omitempty"`

	// Limit The maximum number of entries to return. 0 means no limit.
	Limit *InQueryLimit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Skip the first entries of the data cursor.
	Offset *InQueryOffset `form:"offset,omitempty" json:"offset,omitempty"`

	// Meta Include metadata in the response. Enabled by default. Use false or 0 to omit the meta field.
	Meta *InQueryMeta `form:"meta,omitempty" json:"meta,omitempty"`

	// Stats Controls the inclusion in the returned dictionnary of a "stats" key, containing the selected properties distinct values counts.
	Stats *InQueryStats `form:"stats,omitempty" json:"stats,omitempty"`

	// Orderby Comma-separated list of properties to sort by. Prefix a property with - for descending order (e.g. orderby=nodename,-app).
	Orderby *InQueryOrderby `form:"orderby,omitempty" json:"orderby,omitempty"`

	// Groupby Comma-separated list of properties to group the result by (e.g. groupby=app,svcname).
	Groupby *InQueryGroupby `form:"groupby,omitempty" json:"groupby,omitempty"`
}

// GetNodeParams defines parameters for GetNode.
type GetNodeParams struct {
	// Props A list of properties to include in each data dictionnary.
	Props *InQueryProps `form:"props,omitempty" json:"props,omitempty"`

	// Limit The maximum number of entries to return. 0 means no limit.
	Limit *InQueryLimit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Skip the first entries of the data cursor.
	Offset *InQueryOffset `form:"offset,omitempty" json:"offset,omitempty"`

	// Meta Include metadata in the response. Enabled by default. Use false or 0 to omit the meta field.
	Meta *InQueryMeta `form:"meta,omitempty" json:"meta,omitempty"`

	// Stats Controls the inclusion in the returned dictionnary of a "stats" key, containing the selected properties distinct values counts.
	Stats *InQueryStats `form:"stats,omitempty" json:"stats,omitempty"`

	// Orderby Comma-separated list of properties to sort by. Prefix a property with - for descending order (e.g. orderby=nodename,-app).
	Orderby *InQueryOrderby `form:"orderby,omitempty" json:"orderby,omitempty"`

	// Groupby Comma-separated list of properties to group the result by (e.g. groupby=app,svcname).
	Groupby *InQueryGroupby `form:"groupby,omitempty" json:"groupby,omitempty"`
}

// PostNodeJSONBody defines parameters for PostNode.
type PostNodeJSONBody struct {
	ActionType          *PostNodeJSONBodyActionType `json:"action_type,omitempty"`
	App                 *string                     `json:"app,omitempty"`
	AssetEnv            *string                     `json:"asset_env,omitempty"`
	Assetname           *string                     `json:"assetname,omitempty"`
	BiosVersion         *string                     `json:"bios_version,omitempty"`
	ClusterId           *string                     `json:"cluster_id,omitempty"`
	Collector           *string                     `json:"collector,omitempty"`
	ConnectTo           *string                     `json:"connect_to,omitempty"`
	CpuCores            *int                        `json:"cpu_cores,omitempty"`
	CpuDies             *int                        `json:"cpu_dies,omitempty"`
	CpuFreq             *string                     `json:"cpu_freq,omitempty"`
	CpuModel            *string                     `json:"cpu_model,omitempty"`
	CpuThreads          *int                        `json:"cpu_threads,omitempty"`
	CpuVendor           *string                     `json:"cpu_vendor,omitempty"`
	Enclosure           *string                     `json:"enclosure,omitempty"`
	Enclosureslot       *string                     `json:"enclosureslot,omitempty"`
	Fqdn                *string                     `json:"fqdn,omitempty"`
	Hv                  *string                     `json:"hv,omitempty"`
	Hvpool              *string                     `json:"hvpool,omitempty"`
	Hvvdc               *string                     `json:"hvvdc,omitempty"`
	HwObsAlertDate      *string                     `json:"hw_obs_alert_date,omitempty"`
	HwObsWarnDate       *string                     `json:"hw_obs_warn_date,omitempty"`
	LastBoot            *string                     `json:"last_boot,omitempty"`
	LastComm            *string                     `json:"last_comm,omitempty"`
	ListenerPort        *int                        `json:"listener_port,omitempty"`
	LocAddr             *string                     `json:"loc_addr,omitempty"`
	LocBuilding         *string                     `json:"loc_building,omitempty"`
	LocCity             *string                     `json:"loc_city,omitempty"`
	LocCountry          *string                     `json:"loc_country,omitempty"`
	LocFloor            *string                     `json:"loc_floor,omitempty"`
	LocRack             *string                     `json:"loc_rack,omitempty"`
	LocRoom             *string                     `json:"loc_room,omitempty"`
	LocZip              *string                     `json:"loc_zip,omitempty"`
	MaintenanceEnd      *string                     `json:"maintenance_end,omitempty"`
	Manufacturer        *string                     `json:"manufacturer,omitempty"`
	MemBanks            *int                        `json:"mem_banks,omitempty"`
	MemBytes            *int                        `json:"mem_bytes,omitempty"`
	MemSlots            *int                        `json:"mem_slots,omitempty"`
	Model               *string                     `json:"model,omitempty"`
	NodeEnv             *string                     `json:"node_env,omitempty"`
	NodeFrozen          *bool                       `json:"node_frozen,omitempty"`
	NodeFrozenAt        *string                     `json:"node_frozen_at,omitempty"`
	Nodename            *string                     `json:"nodename,omitempty"`
	Notifications       *bool                       `json:"notifications,omitempty"`
	OsArch              *string                     `json:"os_arch,omitempty"`
	OsConcat            *string                     `json:"os_concat,omitempty"`
	OsKernel            *string                     `json:"os_kernel,omitempty"`
	OsName              *string                     `json:"os_name,omitempty"`
	OsObsAlertDate      *string                     `json:"os_obs_alert_date,omitempty"`
	OsObsWarnDate       *string                     `json:"os_obs_warn_date,omitempty"`
	OsRelease           *string                     `json:"os_release,omitempty"`
	OsVendor            *string                     `json:"os_vendor,omitempty"`
	PowerBreaker1       *string                     `json:"power_breaker1,omitempty"`
	PowerBreaker2       *string                     `json:"power_breaker2,omitempty"`
	PowerCabinet1       *string                     `json:"power_cabinet1,omitempty"`
	PowerCabinet2       *string                     `json:"power_cabinet2,omitempty"`
	PowerProtect        *string                     `json:"power_protect,omitempty"`
	PowerProtectBreaker *string                     `json:"power_protect_breaker,omitempty"`
	PowerSupplyNb       *int                        `json:"power_supply_nb,omitempty"`
	Role                *string                     `json:"role,omitempty"`
	SecZone             *string                     `json:"sec_zone,omitempty"`
	Serial              *string                     `json:"serial,omitempty"`
	SnoozeTill          *string                     `json:"snooze_till,omitempty"`
	SpVersion           *string                     `json:"sp_version,omitempty"`
	Status              *string                     `json:"status,omitempty"`
	TeamInteg           *string                     `json:"team_integ,omitempty"`
	TeamResponsible     *string                     `json:"team_responsible,omitempty"`
	TeamSupport         *string                     `json:"team_support,omitempty"`
	Type                *string                     `json:"type,omitempty"`
	Tz                  *string                     `json:"tz,omitempty"`
	Updated             *string                     `json:"updated,omitempty"`
	Version             *string                     `json:"version,omitempty"`
	WarrantyEnd         *string                     `json:"warranty_end,omitempty"`
}

// PostNodeJSONBodyActionType defines parameters for PostNode.
type PostNodeJSONBodyActionType string

// GetNodeCandidateTagsParams defines parameters for GetNodeCandidateTags.
type GetNodeCandidateTagsParams struct {
	// Props A list of properties to include in each data dictionnary.
	Props *InQueryProps `form:"props,omitempty" json:"props,omitempty"`

	// Limit The maximum number of entries to return. 0 means no limit.
	Limit *InQueryLimit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Skip the first entries of the data cursor.
	Offset *InQueryOffset `form:"offset,omitempty" json:"offset,omitempty"`

	// Meta Include metadata in the response. Enabled by default. Use false or 0 to omit the meta field.
	Meta *InQueryMeta `form:"meta,omitempty" json:"meta,omitempty"`

	// Stats Controls the inclusion in the returned dictionnary of a "stats" key, containing the selected properties distinct values counts.
	Stats *InQueryStats `form:"stats,omitempty" json:"stats,omitempty"`

	// Orderby Comma-separated list of properties to sort by. Prefix a property with - for descending order (e.g. orderby=nodename,-app).
	Orderby *InQueryOrderby `form:"orderby,omitempty" json:"orderby,omitempty"`

	// Groupby Comma-separated list of properties to group the result by (e.g. groupby=app,svcname).
	Groupby *InQueryGroupby `form:"groupby,omitempty" json:"groupby,omitempty"`
}

// GetNodeComplianceCandidateModulesetsParams defines parameters for GetNodeComplianceCandidateModulesets.
type GetNodeComplianceCandidateModulesetsParams struct {
	// Props A list of properties to include in each data dictionnary.
	Props *InQueryProps `form:"props,omitempty" json:"props,omitempty"`

	// Limit The maximum number of entries to return. 0 means no limit.
	Limit *InQueryLimit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Skip the first entries of the data cursor.
	Offset *InQueryOffset `form:"offset,omitempty" json:"offset,omitempty"`

	// Meta Include metadata in the response. Enabled by default. Use false or 0 to omit the meta field.
	Meta *InQueryMeta `form:"meta,omitempty" json:"meta,omitempty"`

	// Stats Controls the inclusion in the returned dictionnary of a "stats" key, containing the selected properties distinct values counts.
	Stats *InQueryStats `form:"stats,omitempty" json:"stats,omitempty"`

	// Orderby Comma-separated list of properties to sort by. Prefix a property with - for descending order (e.g. orderby=nodename,-app).
	Orderby *InQueryOrderby `form:"orderby,omitempty" json:"orderby,omitempty"`

	// Groupby Comma-separated list of properties to group the result by (e.g. groupby=app,svcname).
	Groupby *InQueryGroupby `form:"groupby,omitempty" json:"groupby,omitempty"`
}

// GetNodeComplianceCandidateRulesetsParams defines parameters for GetNodeComplianceCandidateRulesets.
type GetNodeComplianceCandidateRulesetsParams struct {
	// Props A list of properties to include in each data dictionnary.
	Props *InQueryProps `form:"props,omitempty" json:"props,omitempty"`

	// Limit The maximum number of entries to return. 0 means no limit.
	Limit *InQueryLimit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Skip the first entries of the data cursor.
	Offset *InQueryOffset `form:"offset,omitempty" json:"offset,omitempty"`

	// Meta Include metadata in the response. Enabled by default. Use false or 0 to omit the meta field.
	Meta *InQueryMeta `form:"meta,omitempty" json:"meta,omitempty"`

	// Stats Controls the inclusion in the returned dictionnary of a "stats" key, containing the selected properties distinct values counts.
	Stats *InQueryStats `form:"stats,omitempty" json:"stats,omitempty"`

	// Orderby Comma-separated list of properties to sort by. Prefix a property with - for descending order (e.g. orderby=nodename,-app).
	Orderby *InQueryOrderby `form:"orderby,omitempty" json:"orderby,omitempty"`

	// Groupby Comma-separated list of properties to group the result by (e.g. groupby=app,svcname).
	Groupby *InQueryGroupby `form:"groupby,omitempty" json:"groupby,omitempty"`
}

// GetNodeComplianceLogsParams defines parameters for GetNodeComplianceLogs.
type GetNodeComplianceLogsParams struct {
	// Props A list of properties to include in each data dictionnary.
	Props *InQueryProps `form:"props,omitempty" json:"props,omitempty"`
}

// GetNodeComplianceModulesetsParams defines parameters for GetNodeComplianceModulesets.
type GetNodeComplianceModulesetsParams struct {
	// Props A list of properties to include in each data dictionnary.
	Props *InQueryProps `form:"props,omitempty" json:"props,omitempty"`

	// Limit The maximum number of entries to return. 0 means no limit.
	Limit *InQueryLimit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Skip the first entries of the data cursor.
	Offset *InQueryOffset `form:"offset,omitempty" json:"offset,omitempty"`

	// Meta Include metadata in the response. Enabled by default. Use false or 0 to omit the meta field.
	Meta *InQueryMeta `form:"meta,omitempty" json:"meta,omitempty"`

	// Stats Controls the inclusion in the returned dictionnary of a "stats" key, containing the selected properties distinct values counts.
	Stats *InQueryStats `form:"stats,omitempty" json:"stats,omitempty"`

	// Orderby Comma-separated list of properties to sort by. Prefix a property with - for descending order (e.g. orderby=nodename,-app).
	Orderby *InQueryOrderby `form:"orderby,omitempty" json:"orderby,omitempty"`

	// Groupby Comma-separated list of properties to group the result by (e.g. groupby=app,svcname).
	Groupby *InQueryGroupby `form:"groupby,omitempty" json:"groupby,omitempty"`
}

// PostNodeComplianceModulesetJSONBody defines parameters for PostNodeComplianceModuleset.
type PostNodeComplianceModulesetJSONBody = map[string]interface{}

// GetNodeComplianceRulesetsParams defines parameters for GetNodeComplianceRulesets.
type GetNodeComplianceRulesetsParams struct {
	// Props A list of properties to include in each data dictionnary.
	Props *InQueryProps `form:"props,omitempty" json:"props,omitempty"`

	// Limit The maximum number of entries to return. 0 means no limit.
	Limit *InQueryLimit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Skip the first entries of the data cursor.
	Offset *InQueryOffset `form:"offset,omitempty" json:"offset,omitempty"`

	// Meta Include metadata in the response. Enabled by default. Use false or 0 to omit the meta field.
	Meta *InQueryMeta `form:"meta,omitempty" json:"meta,omitempty"`

	// Stats Controls the inclusion in the returned dictionnary of a "stats" key, containing the selected properties distinct values counts.
	Stats *InQueryStats `form:"stats,omitempty" json:"stats,omitempty"`

	// Orderby Comma-separated list of properties to sort by. Prefix a property with - for descending order (e.g. orderby=nodename,-app).
	Orderby *InQueryOrderby `form:"orderby,omitempty" json:"orderby,omitempty"`

	// Groupby Comma-separated list of properties to group the result by (e.g. groupby=app,svcname).
	Groupby *InQueryGroupby `form:"groupby,omitempty" json:"groupby,omitempty"`
}

// PostNodeComplianceRulesetJSONBody defines parameters for PostNodeComplianceRuleset.
type PostNodeComplianceRulesetJSONBody = map[string]interface{}

// GetNodeDisksParams defines parameters for GetNodeDisks.
type GetNodeDisksParams struct {
	// Props A list of properties to include in each data dictionnary.
	Props *InQueryProps `form:"props,omitempty" json:"props,omitempty"`

	// Limit The maximum number of entries to return. 0 means no limit.
	Limit *InQueryLimit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Skip the first entries of the data cursor.
	Offset *InQueryOffset `form:"offset,omitempty" json:"offset,omitempty"`

	// Meta Include metadata in the response. Enabled by default. Use false or 0 to omit the meta field.
	Meta *InQueryMeta `form:"meta,omitempty" json:"meta,omitempty"`

	// Stats Controls the inclusion in the returned dictionnary of a "stats" key, containing the selected properties distinct values counts.
	Stats *InQueryStats `form:"stats,omitempty" json:"stats,omitempty"`

	// Orderby Comma-separated list of properties to sort by. Prefix a property with - for descending order (e.g. orderby=nodename,-app).
	Orderby *InQueryOrderby `form:"orderby,omitempty" json:"orderby,omitempty"`

	// Groupby Comma-separated list of properties to group the result by (e.g. groupby=app,svcname).
	Groupby *InQueryGroupby `form:"groupby,omitempty" json:"groupby,omitempty"`
}

// GetNodeHardwareParams defines parameters for GetNodeHardware.
type GetNodeHardwareParams struct {
	// Props A list of properties to include in each data dictionnary.
	Props *InQueryProps `form:"props,omitempty" json:"props,omitempty"`

	// Limit The maximum number of entries to return. 0 means no limit.
	Limit *InQueryLimit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Skip the first entries of the data cursor.
	Offset *InQueryOffset `form:"offset,omitempty" json:"offset,omitempty"`

	// Meta Include metadata in the response. Enabled by default. Use false or 0 to omit the meta field.
	Meta *InQueryMeta `form:"meta,omitempty" json:"meta,omitempty"`

	// Stats Controls the inclusion in the returned dictionnary of a "stats" key, containing the selected properties distinct values counts.
	Stats *InQueryStats `form:"stats,omitempty" json:"stats,omitempty"`

	// Orderby Comma-separated list of properties to sort by. Prefix a property with - for descending order (e.g. orderby=nodename,-app).
	Orderby *InQueryOrderby `form:"orderby,omitempty" json:"orderby,omitempty"`

	// Groupby Comma-separated list of properties to group the result by (e.g. groupby=app,svcname).
	Groupby *InQueryGroupby `form:"groupby,omitempty" json:"groupby,omitempty"`
}

// GetNodeHbasParams defines parameters for GetNodeHbas.
type GetNodeHbasParams struct {
	// Props A list of properties to include in each data dictionnary.
	Props *InQueryProps `form:"props,omitempty" json:"props,omitempty"`

	// Limit The maximum number of entries to return. 0 means no limit.
	Limit *InQueryLimit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Skip the first entries of the data cursor.
	Offset *InQueryOffset `form:"offset,omitempty" json:"offset,omitempty"`

	// Meta Include metadata in the response. Enabled by default. Use false or 0 to omit the meta field.
	Meta *InQueryMeta `form:"meta,omitempty" json:"meta,omitempty"`

	// Stats Controls the inclusion in the returned dictionnary of a "stats" key, containing the selected properties distinct values counts.
	Stats *InQueryStats `form:"stats,omitempty" json:"stats,omitempty"`

	// Orderby Comma-separated list of properties to sort by. Prefix a property with - for descending order (e.g. orderby=nodename,-app).
	Orderby *InQueryOrderby `form:"orderby,omitempty" json:"orderby,omitempty"`

	// Groupby Comma-separated list of properties to group the result by (e.g. groupby=app,svcname).
	Groupby *InQueryGroupby `form:"groupby,omitempty" json:"groupby,omitempty"`
}

// GetNodeInterfacesParams defines parameters for GetNodeInterfaces.
type GetNodeInterfacesParams struct {
	// Props A list of properties to include in each data dictionnary.
	Props *InQueryProps `form:"props,omitempty" json:"props,omitempty"`

	// Limit The maximum number of entries to return. 0 means no limit.
	Limit *InQueryLimit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Skip the first entries of the data cursor.
	Offset *InQueryOffset `form:"offset,omitempty" json:"offset,omitempty"`

	// Meta Include metadata in the response. Enabled by default. Use false or 0 to omit the meta field.
	Meta *InQueryMeta `form:"meta,omitempty" json:"meta,omitempty"`

	// Stats Controls the inclusion in the returned dictionnary of a "stats" key, containing the selected properties distinct values counts.
	Stats *InQueryStats `form:"stats,omitempty" json:"stats,omitempty"`

	// Orderby Comma-separated list of properties to sort by. Prefix a property with - for descending order (e.g. orderby=nodename,-app).
	Orderby *InQueryOrderby `form:"orderby,omitempty" json:"orderby,omitempty"`

	// Groupby Comma-separated list of properties to group the result by (e.g. groupby=app,svcname).
	Groupby *InQueryGroupby `form:"groupby,omitempty" json:"groupby,omitempty"`
}

// GetNodeIpsParams defines parameters for GetNodeIps.
type GetNodeIpsParams struct {
	// Props A list of properties to include in each data dictionnary.
	Props *InQueryProps `form:"props,omitempty" json:"props,omitempty"`

	// Limit The maximum number of entries to return. 0 means no limit.
	Limit *InQueryLimit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Skip the first entries of the data cursor.
	Offset *InQueryOffset `form:"offset,omitempty" json:"offset,omitempty"`

	// Meta Include metadata in the response. Enabled by default. Use false or 0 to omit the meta field.
	Meta *InQueryMeta `form:"meta,omitempty" json:"meta,omitempty"`

	// Stats Controls the inclusion in the returned dictionnary of a "stats" key, containing the selected properties distinct values counts.
	Stats *InQueryStats `form:"stats,omitempty" json:"stats,omitempty"`

	// Orderby Comma-separated list of properties to sort by. Prefix a property with - for descending order (e.g. orderby=nodename,-app).
	Orderby *InQueryOrderby `form:"orderby,omitempty" json:"orderby,omitempty"`

	// Groupby Comma-separated list of properties to group the result by (e.g. groupby=app,svcname).
	Groupby *InQueryGroupby `form:"groupby,omitempty" json:"groupby,omitempty"`
}

// PostNodeSnoozeJSONBody defines parameters for PostNodeSnooze.
type PostNodeSnoozeJSONBody struct {
	// Duration Duration string (e.g. "1h", "30m", "2d"). Omit to unsnooze.
	Duration *string `json:"duration,omitempty"`
}

// GetNodeTagsParams defines parameters for GetNodeTags.
type GetNodeTagsParams struct {
	// Props A list of properties to include in each data dictionnary.
	Props *InQueryProps `form:"props,omitempty" json:"props,omitempty"`

	// Limit The maximum number of entries to return. 0 means no limit.
	Limit *InQueryLimit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Skip the first entries of the data cursor.
	Offset *InQueryOffset `form:"offset,omitempty" json:"offset,omitempty"`

	// Meta Include metadata in the response. Enabled by default. Use false or 0 to omit the meta field.
	Meta *InQueryMeta `form:"meta,omitempty" json:"meta,omitempty"`

	// Stats Controls the inclusion in the returned dictionnary of a "stats" key, containing the selected properties distinct values counts.
	Stats *InQueryStats `form:"stats,omitempty" json:"stats,omitempty"`

	// Orderby Comma-separated list of properties to sort by. Prefix a property with - for descending order (e.g. orderby=nodename,-app).
	Orderby *InQueryOrderby `form:"orderby,omitempty" json:"orderby,omitempty"`

	// Groupby Comma-separated list of properties to group the result by (e.g. groupby=app,svcname).
	Groupby *InQueryGroupby `form:"groupby,omitempty" json:"groupby,omitempty"`
}

// GetServicesParams defines parameters for GetServices.
type GetServicesParams struct {
	// Props A list of properties to include in each data dictionnary.
	Props *InQueryProps `form:"props,omitempty" json:"props,omitempty"`

	// Limit The maximum number of entries to return. 0 means no limit.
	Limit *InQueryLimit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Skip the first entries of the data cursor.
	Offset *InQueryOffset `form:"offset,omitempty" json:"offset,omitempty"`

	// Meta Include metadata in the response. Enabled by default. Use false or 0 to omit the meta field.
	Meta *InQueryMeta `form:"meta,omitempty" json:"meta,omitempty"`

	// Stats Controls the inclusion in the returned dictionnary of a "stats" key, containing the selected properties distinct values counts.
	Stats *InQueryStats `form:"stats,omitempty" json:"stats,omitempty"`

	// Orderby Comma-separated list of properties to sort by. Prefix a property with - for descending order (e.g. orderby=nodename,-app).
	Orderby *InQueryOrderby `form:"orderby,omitempty" json:"orderby,omitempty"`

	// Groupby Comma-separated list of properties to group the result by (e.g. groupby=app,svcname).
	Groupby *InQueryGroupby `form:"groupby,omitempty" json:"groupby,omitempty"`
}

// GetServiceParams defines parameters for GetService.
type GetServiceParams struct {
	// Props A list of properties to include in each data dictionnary.
	Props *InQueryProps `form:"props,omitempty" json:"props,omitempty"`

	// Limit The maximum number of entries to return. 0 means no limit.
	Limit *InQueryLimit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Skip the first entries of the data cursor.
	Offset *InQueryOffset `form:"offset,omitempty" json:"offset,omitempty"`

	// Meta Include metadata in the response. Enabled by default. Use false or 0 to omit the meta field.
	Meta *InQueryMeta `form:"meta,omitempty" json:"meta,omitempty"`

	// Stats Controls the inclusion in the returned dictionnary of a "stats" key, containing the selected properties distinct values counts.
	Stats *InQueryStats `form:"stats,omitempty" json:"stats,omitempty"`

	// Orderby Comma-separated list of properties to sort by. Prefix a property with - for descending order (e.g. orderby=nodename,-app).
	Orderby *InQueryOrderby `form:"orderby,omitempty" json:"orderby,omitempty"`

	// Groupby Comma-separated list of properties to group the result by (e.g. groupby=app,svcname).
	Groupby *InQueryGroupby `form:"groupby,omitempty" json:"groupby,omitempty"`
}

// GetServiceCandidateTagsParams defines parameters for GetServiceCandidateTags.
type GetServiceCandidateTagsParams struct {
	// Props A list of properties to include in each data dictionnary.
	Props *InQueryProps `form:"props,omitempty" json:"props,omitempty"`

	// Limit The maximum number of entries to return. 0 means no limit.
	Limit *InQueryLimit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Skip the first entries of the data cursor.
	Offset *InQueryOffset `form:"offset,omitempty" json:"offset,omitempty"`

	// Meta Include metadata in the response. Enabled by default. Use false or 0 to omit the meta field.
	Meta *InQueryMeta `form:"meta,omitempty" json:"meta,omitempty"`

	// Stats Controls the inclusion in the returned dictionnary of a "stats" key, containing the selected properties distinct values counts.
	Stats *InQueryStats `form:"stats,omitempty" json:"stats,omitempty"`

	// Orderby Comma-separated list of properties to sort by. Prefix a property with - for descending order (e.g. orderby=nodename,-app).
	Orderby *InQueryOrderby `form:"orderby,omitempty" json:"orderby,omitempty"`

	// Groupby Comma-separated list of properties to group the result by (e.g. groupby=app,svcname).
	Groupby *InQueryGroupby `form:"groupby,omitempty" json:"groupby,omitempty"`
}

// GetServiceTagsParams defines parameters for GetServiceTags.
type GetServiceTagsParams struct {
	// Props A list of properties to include in each data dictionnary.
	Props *InQueryProps `form:"props,omitempty" json:"props,omitempty"`

	// Limit The maximum number of entries to return. 0 means no limit.
	Limit *InQueryLimit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Skip the first entries of the data cursor.
	Offset *InQueryOffset `form:"offset,omitempty" json:"offset,omitempty"`

	// Meta Include metadata in the response. Enabled by default. Use false or 0 to omit the meta field.
	Meta *InQueryMeta `form:"meta,omitempty" json:"meta,omitempty"`

	// Stats Controls the inclusion in the returned dictionnary of a "stats" key, containing the selected properties distinct values counts.
	Stats *InQueryStats `form:"stats,omitempty" json:"stats,omitempty"`

	// Orderby Comma-separated list of properties to sort by. Prefix a property with - for descending order (e.g. orderby=nodename,-app).
	Orderby *InQueryOrderby `form:"orderby,omitempty" json:"orderby,omitempty"`

	// Groupby Comma-separated list of properties to group the result by (e.g. groupby=app,svcname).
	Groupby *InQueryGroupby `form:"groupby,omitempty" json:"groupby,omitempty"`
}

// GetServicesInstancesParams defines parameters for GetServicesInstances.
type GetServicesInstancesParams struct {
	// Props A list of properties to include in each data dictionnary.
	Props *InQueryProps `form:"props,omitempty" json:"props,omitempty"`

	// Limit The maximum number of entries to return. 0 means no limit.
	Limit *InQueryLimit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Skip the first entries of the data cursor.
	Offset *InQueryOffset `form:"offset,omitempty" json:"offset,omitempty"`

	// Meta Include metadata in the response. Enabled by default. Use false or 0 to omit the meta field.
	Meta *InQueryMeta `form:"meta,omitempty" json:"meta,omitempty"`

	// Stats Controls the inclusion in the returned dictionnary of a "stats" key, containing the selected properties distinct values counts.
	Stats *InQueryStats `form:"stats,omitempty" json:"stats,omitempty"`

	// Orderby Comma-separated list of properties to sort by. Prefix a property with - for descending order (e.g. orderby=nodename,-app).
	Orderby *InQueryOrderby `form:"orderby,omitempty" json:"orderby,omitempty"`

	// Groupby Comma-separated list of properties to group the result by (e.g. groupby=app,svcname).
	Groupby *InQueryGroupby `form:"groupby,omitempty" json:"groupby,omitempty"`
}

// GetServicesInstanceParams defines parameters for GetServicesInstance.
type GetServicesInstanceParams struct {
	// Props A list of properties to include in each data dictionnary.
	Props *InQueryProps `form:"props,omitempty" json:"props,omitempty"`

	// Limit The maximum number of entries to return. 0 means no limit.
	Limit *InQueryLimit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Skip the first entries of the data cursor.
	Offset *InQueryOffset `form:"offset,omitempty" json:"offset,omitempty"`

	// Meta Include metadata in the response. Enabled by default. Use false or 0 to omit the meta field.
	Meta *InQueryMeta `form:"meta,omitempty" json:"meta,omitempty"`

	// Stats Controls the inclusion in the returned dictionnary of a "stats" key, containing the selected properties distinct values counts.
	Stats *InQueryStats `form:"stats,omitempty" json:"stats,omitempty"`

	// Orderby Comma-separated list of properties to sort by. Prefix a property with - for descending order (e.g. orderby=nodename,-app).
	Orderby *InQueryOrderby `form:"orderby,omitempty" json:"orderby,omitempty"`

	// Groupby Comma-separated list of properties to group the result by (e.g. groupby=app,svcname).
	Groupby *InQueryGroupby `form:"groupby,omitempty" json:"groupby,omitempty"`
}

// GetServicesInstancesStatusLogParams defines parameters for GetServicesInstancesStatusLog.
type GetServicesInstancesStatusLogParams struct {
	// Props A list of properties to include in each data dictionnary.
	Props *InQueryProps `form:"props,omitempty" json:"props,omitempty"`

	// Limit The maximum number of entries to return. 0 means no limit.
	Limit *InQueryLimit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Skip the first entries of the data cursor.
	Offset *InQueryOffset `form:"offset,omitempty" json:"offset,omitempty"`

	// Meta Include metadata in the response. Enabled by default. Use false or 0 to omit the meta field.
	Meta *InQueryMeta `form:"meta,omitempty" json:"meta,omitempty"`

	// Stats Controls the inclusion in the returned dictionnary of a "stats" key, containing the selected properties distinct values counts.
	Stats *InQueryStats `form:"stats,omitempty" json:"stats,omitempty"`

	// Orderby Comma-separated list of properties to sort by. Prefix a property with - for descending order (e.g. orderby=nodename,-app).
	Orderby *InQueryOrderby `form:"orderby,omitempty" json:"orderby,omitempty"`

	// Groupby Comma-separated list of properties to group the result by (e.g. groupby=app,svcname).
	Groupby *InQueryGroupby `form:"groupby,omitempty" json:"groupby,omitempty"`
}

// GetTagsParams defines parameters for GetTags.
type GetTagsParams struct {
	// Props A list of properties to include in each data dictionnary.
	Props *InQueryProps `form:"props,omitempty" json:"props,omitempty"`

	// Limit The maximum number of entries to return. 0 means no limit.
	Limit *InQueryLimit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Skip the first entries of the data cursor.
	Offset *InQueryOffset `form:"offset,omitempty" json:"offset,omitempty"`

	// Meta Include metadata in the response. Enabled by default. Use false or 0 to omit the meta field.
	Meta *InQueryMeta `form:"meta,omitempty" json:"meta,omitempty"`

	// Stats Controls the inclusion in the returned dictionnary of a "stats" key, containing the selected properties distinct values counts.
	Stats *InQueryStats `form:"stats,omitempty" json:"stats,omitempty"`

	// Orderby Comma-separated list of properties to sort by. Prefix a property with - for descending order (e.g. orderby=nodename,-app).
	Orderby *InQueryOrderby `form:"orderby,omitempty" json:"orderby,omitempty"`

	// Groupby Comma-separated list of properties to group the result by (e.g. groupby=app,svcname).
	Groupby *InQueryGroupby `form:"groupby,omitempty" json:"groupby,omitempty"`
}

// GetTagsNodesParams defines parameters for GetTagsNodes.
type GetTagsNodesParams struct {
	// Props A list of properties to include in each data dictionnary.
	Props *InQueryProps `form:"props,omitempty" json:"props,omitempty"`

	// Limit The maximum number of entries to return. 0 means no limit.
	Limit *InQueryLimit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Skip the first entries of the data cursor.
	Offset *InQueryOffset `form:"offset,omitempty" json:"offset,omitempty"`

	// Meta Include metadata in the response. Enabled by default. Use false or 0 to omit the meta field.
	Meta *InQueryMeta `form:"meta,omitempty" json:"meta,omitempty"`

	// Stats Controls the inclusion in the returned dictionnary of a "stats" key, containing the selected properties distinct values counts.
	Stats *InQueryStats `form:"stats,omitempty" json:"stats,omitempty"`

	// Orderby Comma-separated list of properties to sort by. Prefix a property with - for descending order (e.g. orderby=nodename,-app).
	Orderby *InQueryOrderby `form:"orderby,omitempty" json:"orderby,omitempty"`

	// Groupby Comma-separated list of properties to group the result by (e.g. groupby=app,svcname).
	Groupby *InQueryGroupby `form:"groupby,omitempty" json:"groupby,omitempty"`
}

// GetTagsServicesParams defines parameters for GetTagsServices.
type GetTagsServicesParams struct {
	// Props A list of properties to include in each data dictionnary.
	Props *InQueryProps `form:"props,omitempty" json:"props,omitempty"`

	// Limit The maximum number of entries to return. 0 means no limit.
	Limit *InQueryLimit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Skip the first entries of the data cursor.
	Offset *InQueryOffset `form:"offset,omitempty" json:"offset,omitempty"`

	// Meta Include metadata in the response. Enabled by default. Use false or 0 to omit the meta field.
	Meta *InQueryMeta `form:"meta,omitempty" json:"meta,omitempty"`

	// Stats Controls the inclusion in the returned dictionnary of a "stats" key, containing the selected properties distinct values counts.
	Stats *InQueryStats `form:"stats,omitempty" json:"stats,omitempty"`

	// Orderby Comma-separated list of properties to sort by. Prefix a property with - for descending order (e.g. orderby=nodename,-app).
	Orderby *InQueryOrderby `form:"orderby,omitempty" json:"orderby,omitempty"`

	// Groupby Comma-separated list of properties to group the result by (e.g. groupby=app,svcname).
	Groupby *InQueryGroupby `form:"groupby,omitempty" json:"groupby,omitempty"`
}

// GetTagParams defines parameters for GetTag.
type GetTagParams struct {
	// Props A list of properties to include in each data dictionnary.
	Props *InQueryProps `form:"props,omitempty" json:"props,omitempty"`
}

// GetTagNodesParams defines parameters for GetTagNodes.
type GetTagNodesParams struct {
	// Props A list of properties to include in each data dictionnary.
	Props *InQueryProps `form:"props,omitempty" json:"props,omitempty"`

	// Limit The maximum number of entries to return. 0 means no limit.
	Limit *InQueryLimit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Skip the first entries of the data cursor.
	Offset *InQueryOffset `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetTagServicesParams defines parameters for GetTagServices.
type GetTagServicesParams struct {
	// Props A list of properties to include in each data dictionnary.
	Props *InQueryProps `form:"props,omitempty" json:"props,omitempty"`

	// Limit The maximum number of entries to return. 0 means no limit.
	Limit *InQueryLimit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Skip the first entries of the data cursor.
	Offset *InQueryOffset `form:"offset,omitempty" json:"offset,omitempty"`

	// Meta Include metadata in the response. Enabled by default. Use false or 0 to omit the meta field.
	Meta *InQueryMeta `form:"meta,omitempty" json:"meta,omitempty"`

	// Stats Controls the inclusion in the returned dictionnary of a "stats" key, containing the selected properties distinct values counts.
	Stats *InQueryStats `form:"stats,omitempty" json:"stats,omitempty"`

	// Orderby Comma-separated list of properties to sort by. Prefix a property with - for descending order (e.g. orderby=nodename,-app).
	Orderby *InQueryOrderby `form:"orderby,omitempty" json:"orderby,omitempty"`

	// Groupby Comma-separated list of properties to group the result by (e.g. groupby=app,svcname).
	Groupby *InQueryGroupby `form:"groupby,omitempty" json:"groupby,omitempty"`
}

// PostAppsJSONRequestBody defines body for PostApps for application/json ContentType.
type PostAppsJSONRequestBody PostAppsJSONBody

// PostAppJSONRequestBody defines body for PostApp for application/json ContentType.
type PostAppJSONRequestBody PostAppJSONBody

// PostAuthNodeJSONRequestBody defines body for PostAuthNode for application/json ContentType.
type PostAuthNodeJSONRequestBody PostAuthNodeJSONBody

// PostNodesJSONRequestBody defines body for PostNodes for application/json ContentType.
type PostNodesJSONRequestBody PostNodesJSONBody

// PostNodeJSONRequestBody defines body for PostNode for application/json ContentType.
type PostNodeJSONRequestBody PostNodeJSONBody

// PostNodeComplianceModulesetJSONRequestBody defines body for PostNodeComplianceModuleset for application/json ContentType.
type PostNodeComplianceModulesetJSONRequestBody = PostNodeComplianceModulesetJSONBody

// PostNodeComplianceRulesetJSONRequestBody defines body for PostNodeComplianceRuleset for application/json ContentType.
type PostNodeComplianceRulesetJSONRequestBody = PostNodeComplianceRulesetJSONBody

// PostNodeSnoozeJSONRequestBody defines body for PostNodeSnooze for application/json ContentType.
type PostNodeSnoozeJSONRequestBody PostNodeSnoozeJSONBody

// AsListResponseData0 returns the union data inside the ListResponse_Data as a ListResponseData0
func (t ListResponse_Data) AsListResponseData0() (ListResponseData0, error) {
	var body ListResponseData0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromListResponseData0 overwrites any union data inside the ListResponse_Data as the provided ListResponseData0
func (t *ListResponse_Data) FromListResponseData0(v ListResponseData0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeListResponseData0 performs a merge with any union data inside the ListResponse_Data, using the provided ListResponseData0
func (t *ListResponse_Data) MergeListResponseData0(v ListResponseData0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsListResponseData1 returns the union data inside the ListResponse_Data as a ListResponseData1
func (t ListResponse_Data) AsListResponseData1() (ListResponseData1, error) {
	var body ListResponseData1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromListResponseData1 overwrites any union data inside the ListResponse_Data as the provided ListResponseData1
func (t *ListResponse_Data) FromListResponseData1(v ListResponseData1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeListResponseData1 performs a merge with any union data inside the ListResponse_Data, using the provided ListResponseData1
func (t *ListResponse_Data) MergeListResponseData1(v ListResponseData1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ListResponse_Data) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ListResponse_Data) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
