// Package feeder provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package feeder

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /checks)
	PostChecks(ctx echo.Context) error

	// (POST /daemon/ping)
	PostDaemonPing(ctx echo.Context) error

	// (POST /daemon/status)
	PostDaemonStatus(ctx echo.Context) error

	// (POST /instance/action)
	PostInstanceAction(ctx echo.Context) error

	// (PUT /instance/action)
	PutInstanceActionEnd(ctx echo.Context) error

	// (POST /instance/resource_info)
	PostInstanceResourceInfo(ctx echo.Context) error

	// (POST /instance/status)
	PostInstanceStatus(ctx echo.Context, params PostInstanceStatusParams) error

	// (GET /node/actionq)
	GetNodeActionQueued(ctx echo.Context) error

	// (POST /node/actionq/done)
	PostNodeActionQueuedDone(ctx echo.Context) error

	// (POST /node/actionq/running)
	PostNodeActionQueuedRunning(ctx echo.Context) error

	// (POST /node/disk)
	PostNodeDisk(ctx echo.Context) error

	// (POST /node/sysreport)
	PostNodeSysReport(ctx echo.Context) error

	// (POST /node/system)
	PostSystem(ctx echo.Context) error

	// (POST /object/config)
	PostObjectConfig(ctx echo.Context) error

	// (GET /openapi.json)
	GetSwagger(ctx echo.Context) error

	// (GET /version)
	GetVersion(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// PostChecks converts echo context to params.
func (w *ServerInterfaceWrapper) PostChecks(ctx echo.Context) error {
	var err error

	ctx.Set(string(BasicAuthScopes), []string{})

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostChecks(ctx)
	return err
}

// PostDaemonPing converts echo context to params.
func (w *ServerInterfaceWrapper) PostDaemonPing(ctx echo.Context) error {
	var err error

	ctx.Set(string(BasicAuthScopes), []string{})

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostDaemonPing(ctx)
	return err
}

// PostDaemonStatus converts echo context to params.
func (w *ServerInterfaceWrapper) PostDaemonStatus(ctx echo.Context) error {
	var err error

	ctx.Set(string(BasicAuthScopes), []string{})

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostDaemonStatus(ctx)
	return err
}

// PostInstanceAction converts echo context to params.
func (w *ServerInterfaceWrapper) PostInstanceAction(ctx echo.Context) error {
	var err error

	ctx.Set(string(BasicAuthScopes), []string{})

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostInstanceAction(ctx)
	return err
}

// PutInstanceActionEnd converts echo context to params.
func (w *ServerInterfaceWrapper) PutInstanceActionEnd(ctx echo.Context) error {
	var err error

	ctx.Set(string(BasicAuthScopes), []string{})

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PutInstanceActionEnd(ctx)
	return err
}

// PostInstanceResourceInfo converts echo context to params.
func (w *ServerInterfaceWrapper) PostInstanceResourceInfo(ctx echo.Context) error {
	var err error

	ctx.Set(string(BasicAuthScopes), []string{})

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostInstanceResourceInfo(ctx)
	return err
}

// PostInstanceStatus converts echo context to params.
func (w *ServerInterfaceWrapper) PostInstanceStatus(ctx echo.Context) error {
	var err error

	ctx.Set(string(BasicAuthScopes), []string{})

	ctx.Set(string(BearerAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params PostInstanceStatusParams
	// ------------- Optional query parameter "sync" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sync", ctx.QueryParams(), &params.Sync, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter sync: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostInstanceStatus(ctx, params)
	return err
}

// GetNodeActionQueued converts echo context to params.
func (w *ServerInterfaceWrapper) GetNodeActionQueued(ctx echo.Context) error {
	var err error

	ctx.Set(string(BasicAuthScopes), []string{})

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetNodeActionQueued(ctx)
	return err
}

// PostNodeActionQueuedDone converts echo context to params.
func (w *ServerInterfaceWrapper) PostNodeActionQueuedDone(ctx echo.Context) error {
	var err error

	ctx.Set(string(BasicAuthScopes), []string{})

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostNodeActionQueuedDone(ctx)
	return err
}

// PostNodeActionQueuedRunning converts echo context to params.
func (w *ServerInterfaceWrapper) PostNodeActionQueuedRunning(ctx echo.Context) error {
	var err error

	ctx.Set(string(BasicAuthScopes), []string{})

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostNodeActionQueuedRunning(ctx)
	return err
}

// PostNodeDisk converts echo context to params.
func (w *ServerInterfaceWrapper) PostNodeDisk(ctx echo.Context) error {
	var err error

	ctx.Set(string(BasicAuthScopes), []string{})

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostNodeDisk(ctx)
	return err
}

// PostNodeSysReport converts echo context to params.
func (w *ServerInterfaceWrapper) PostNodeSysReport(ctx echo.Context) error {
	var err error

	ctx.Set(string(BasicAuthScopes), []string{})

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostNodeSysReport(ctx)
	return err
}

// PostSystem converts echo context to params.
func (w *ServerInterfaceWrapper) PostSystem(ctx echo.Context) error {
	var err error

	ctx.Set(string(BasicAuthScopes), []string{})

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostSystem(ctx)
	return err
}

// PostObjectConfig converts echo context to params.
func (w *ServerInterfaceWrapper) PostObjectConfig(ctx echo.Context) error {
	var err error

	ctx.Set(string(BasicAuthScopes), []string{})

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostObjectConfig(ctx)
	return err
}

// GetSwagger converts echo context to params.
func (w *ServerInterfaceWrapper) GetSwagger(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetSwagger(ctx)
	return err
}

// GetVersion converts echo context to params.
func (w *ServerInterfaceWrapper) GetVersion(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetVersion(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(options.BaseURL+"/checks", wrapper.PostChecks, options.OperationMiddlewares["PostChecks"]...)
	router.POST(options.BaseURL+"/daemon/ping", wrapper.PostDaemonPing, options.OperationMiddlewares["PostDaemonPing"]...)
	router.POST(options.BaseURL+"/daemon/status", wrapper.PostDaemonStatus, options.OperationMiddlewares["PostDaemonStatus"]...)
	router.POST(options.BaseURL+"/instance/action", wrapper.PostInstanceAction, options.OperationMiddlewares["PostInstanceAction"]...)
	router.PUT(options.BaseURL+"/instance/action", wrapper.PutInstanceActionEnd, options.OperationMiddlewares["PutInstanceActionEnd"]...)
	router.POST(options.BaseURL+"/instance/resource_info", wrapper.PostInstanceResourceInfo, options.OperationMiddlewares["PostInstanceResourceInfo"]...)
	router.POST(options.BaseURL+"/instance/status", wrapper.PostInstanceStatus, options.OperationMiddlewares["PostInstanceStatus"]...)
	router.GET(options.BaseURL+"/node/actionq", wrapper.GetNodeActionQueued, options.OperationMiddlewares["GetNodeActionQueued"]...)
	router.POST(options.BaseURL+"/node/actionq/done", wrapper.PostNodeActionQueuedDone, options.OperationMiddlewares["PostNodeActionQueuedDone"]...)
	router.POST(options.BaseURL+"/node/actionq/running", wrapper.PostNodeActionQueuedRunning, options.OperationMiddlewares["PostNodeActionQueuedRunning"]...)
	router.POST(options.BaseURL+"/node/disk", wrapper.PostNodeDisk, options.OperationMiddlewares["PostNodeDisk"]...)
	router.POST(options.BaseURL+"/node/sysreport", wrapper.PostNodeSysReport, options.OperationMiddlewares["PostNodeSysReport"]...)
	router.POST(options.BaseURL+"/node/system", wrapper.PostSystem, options.OperationMiddlewares["PostSystem"]...)
	router.POST(options.BaseURL+"/object/config", wrapper.PostObjectConfig, options.OperationMiddlewares["PostObjectConfig"]...)
	router.GET(options.BaseURL+"/openapi.json", wrapper.GetSwagger, options.OperationMiddlewares["GetSwagger"]...)
	router.GET(options.BaseURL+"/version", wrapper.GetVersion, options.OperationMiddlewares["GetVersion"]...)

}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7FtZcxu5Ef4rqEkeNlW0KEvOQ/TmM+UkZXtFb/Jgq1gg0BxiPQOMcdDmuvjfU7jmxHAoWfRuYj9ZHGD6",
	"+LrR6GP8JSOirAQHrlV29SWrsMQlaJDuF+M/G5C7xY4T/zO7yj7aJ9ks47iE7CpTdm2WKbKBEttNelfZ",
	"5yshCsA82+/3s0yCqgRX4Ig+Oj+3/xDBNXBt/8RVVTCCNRN8/qsS3D5rCP5Zwjq7yv40bySd+1U1fyPF",
	"qoDSc6GgiGSVJZNdZU8wRdfw0YDS2X6WPTp/+C24/sKx0Rsh2W9APdvLb8H2hZArRilwy/Ov3wbgl1yD",
	"5LhAC5BbkOi5lEJa/s8wlIK/YTx/TAhUGuitxKmkqEBq5r2FCwrLT0xvlpjYF5YfDRhPsStOwZRGYo1I",
	"YZQGieyLCtk3UQWcMp4j/yryhFQ2y5iGUg1JtUk4N59Fr1ZaMp5bJcMDLCXe2d9i9SsQ7SQVRi+J4GuW",
	"j0vptyNLXSG9wRpJ+GiYBIXevF68RXNcsbnfNA+0RsVt0ZqWtHngX0tZljoDIqWxNgppVoLSuKwsmkWB",
	"VoAkrCWoDVC0Fh6mxu4L99YPy/8fWP6Qufcx5juxHhNPoC/g2w2gFeSMIyER8GgBpzIo/Z5ns57VcU1p",
	"oA6W+XbIQm8AEVGWmFNUMA4Iy9yU7j5r4TZpRSflkLoXPkhdnwTEOLp+8fTy8vJvrzAXFpYS65QJiOwo",
	"U9+Kswx4wpVbEN2BmVXf39tR7UOh3dvsX4xD0qslC4AM2FRYb9ILLKFSUMeuJUSWjKq0TWtPUaLYAkVu",
	"Z4KCAqVsdDDGcx9ucM48KlhYno29uCxE4jT7XytAffdLEYqiJfnbRR8HNnhrTwtwhJViOQeKqLE0UAsP",
	"76cJJluQKnkG7cuiAq62BJGCAdeIYo1RfGFAyyVsLiTR7OqdN/csHsxwDL2xg/1qb2mkCJ4fdO9ZKZ42",
	"fwhqC3UQj958M4has6zluYNb41bnOIVj0olbBnAxpmIUsTUqAXPG87UpRnx7wiEnXG64bFYKdGKpZ7II",
	"r/TY+7eiyTogB1nGUQ4pdPs+7wI+cu56ErldKS7PmPowJErT+o8AWgoKRXIl3M2jEUtCPnbbKPabc68Q",
	"bq8yxvXlRWNnxjXk4BJeo6AtWGtlC5wKOQ2PM0xb2MA/0K4JRV1nFqEUnC+50pgTuAYljCTwkq/FEF4W",
	"ntb3RHf5A+zU4eUkYltcGAtZXzm7P66mZO5fPfIYh/Ku7SQ9huaoB2hRiULku2mOwS4Ou0PQL+rj3fNp",
	"rNsFcvPiqGynDulOooZNSqlXgoI9ogf0OSrZcMf8iJR0lr12fz2ts+heelhVSajsFRxqjMEaldXSJa2H",
	"FrsOP5kuAt8m960L+Lws8ed0OPCrnbSqv6qxzDshvrWhFJxpIYEuZTjeSyIMH9ktJNmA0hJruF0aJ/Gn",
	"VhVTx7/VTiezG0VEBbdD75aHLuWYb4TSTzdAUp65xUXXnPGPlCi931ssb+UKPXnd6zMvwZjYTX8kXfSq",
	"40rc46pYdLsy9gje7QL2nkrTE4Y6D2ij3uFw15hnLIqTDeZ5L1okNRcSsXAjHAPA+O0gYcuEUUtTUayB",
	"LrHuHEv78IHNaJOVxx3eOZkpwnUTEZywRGg8Dgyg4bMeyvYYbUyJ+QMJmOJVAQg+VwXm2Jd4FRC2ZgRp",
	"gfSGKSQIMVICJ2AdW2/gPa88v7P303o4CVIy/+y6TE0vpOc5vkpM30LgO1S3MhQbSTrr5lWK0x34HKpX",
	"tmQ5VuVsyYgQqdy3EasLRs2iIdhScFaDerCSadvlmfBV42h9F1qFEpQpNKqkIKAUULTauTLc8k60re7V",
	"gHIsAVCagpQjlSMVRh+Jdhdh6YrDQKBmMgXkteE8eYUlOzrxEuk0YpFvHozEUTzYnCy+Dl7HlsGUIokg",
	"j5uFo7LbzsGfkikST8m12KlrqITUiXQbCggF+PGJ1poV3SJ2xTh247uJUB2YBQopUStMPuA80YHBkqTz",
	"SncdFsUtD8loJFMsP4DB4XJqImfwsaW515xKgbJnnEJE7ZRO3VgtpI7yprj/qHKppVQvCW4W4DMuK+sI",
	"2fnZ+dnDSeuP38uu30qMZHq3sNKGnhtWjDw2vpxwWrhet33a8NpoXflGO5Yg427/60X0hH/8520cJjsS",
	"brVPY7+f1R0MzbRTLOYlawAKEuGKtQx4lV2enZ89clluBdwu+kfnmS+DnBZz0pQTQiVyjDdGbZDf5G4A",
	"i7ZLMF5Su9oUJB5NUPqJoLv7G8U2DPZdi2lpoD9lv/BD4K4Gr//ZMWF29a5jvHc3+9mXjoHe3eytE+Bc",
	"Wb8IAN1YGnM/KppX8Q5IQnbtJ0d17TA2WRzBs1UpnQ7TFpOjcL0YI1rvmycm4PtZdnH+aIhQyZRiPO8h",
	"E+dsszATDGCHVaZQLeTX2BPnFsCOOZtc7w4GPWjFRWzyn9aOgc39WrI303bfdZxPv2w3NZ+eTO192Ppe",
	"ZGrvZes7j8N77ab78pFYz86bIW3aS574aUs9cLHujFHOtsBj+8CG3RF/iY3Ux3HidAqPicna0X5yj1z7",
	"M5XEIL497UP4e3a8WVaZhIs95/RuDmZ6/vXcVY9/CBdLuoD/JOBH5PGRp258xwQwHYB+cX0vJCQiEuxf",
	"kQCKBJAlMBGAOkO00/hIktVdPSatpE2trSMNvua5f+tMZQ8LLWTTQ7w4e9jYJaQ2FGt8NmGWOpNof6z6",
	"Lo1zs2Xe/pjVanJKc94mCzk/YMiAinJTH6QMIaDU2hTFDv2kdpxspODCqL/49PJimlLzKVeMKegn3Kf0",
	"XYYYm26HxOaj5RymcF04c9Ctj3FU7FDZ68c9NnoDXFvfAdq0Cruu/HfQrwQNt4/vHGVpp7gXl+y2uhKp",
	"hi0Kf2e85zR0ZdNhQ4HuIy6BANsm2rLDsNEH23WAT3P8B43mu9/9zYX/+1pGttq8SeNE9BEmH7j4VADN",
	"QXn7VBphTv3FIw13hlqLohCfbMXb9IBRwZQ+O9J8se98egtGTv+7RqTx46rjkiRnRvuOQn7+b7wtDljG",
	"fddxGlM0n57c1QBj+pwwFXKwq52STRc/3UsUSnu8680HUG7GAoegLk2hWYWlntuk70GcKB+HdsPirmjX",
	"ivwoV6IXxHHAuAv4TdZJidiC3I04wcLTOs1BC4J+hd2dCljjif8g8l36Qve/chwfjEMb45hA3Plk7jQ+",
	"0mHx1fXpt4rGYdpzFnUNOf0gH198wnnuBk1flYZP/vcan2r/IVw7wlWZVcFIwKs1M0yWPxK0kRzhirU+",
	"+hmg+e966WRFTeR+P+VMPd/CFV6xgrkR6s3ee6Hcxv6CkUV2lZ3Ns/3N/r8BAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
