// Package feeder provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package feeder

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BasicAuthScopes  basicAuthContextKey  = "basicAuth.Scopes"
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Action The begin or end action request
type Action struct {
	Action string `json:"action"`

	// Argv the command line arguments
	Argv []string `json:"argv"`

	// Begin begin action timestamp in RFC3339Nano format
	Begin string `json:"begin"`
	Cron  bool   `json:"cron"`

	// End end action timestamp in RFC3339Nano format
	End    string       `json:"end"`
	Lines  []ActionLine `json:"lines"`
	Origin string       `json:"origin"`
	Path   string       `json:"path"`

	// Pid action pid
	Pid string `json:"pid"`

	// Rids the action resolved rids
	Rids        string `json:"rids"`
	SessionUuid string `json:"session_uuid"`

	// Status action status
	Status string `json:"status"`

	// StatusLog describe the command line
	StatusLog string `json:"status_log"`

	// Uuid action uuid that have been assigned during the action begin
	Uuid string `json:"uuid"`

	// Version the opensvc client data version
	Version string `json:"version"`
}

// ActionLine defines model for ActionLine.
type ActionLine struct {
	// Begin begin action timestamp
	Begin string `json:"begin"`

	// Pid the action line pid if meaningful
	Pid       string `json:"pid"`
	Rid       string `json:"rid"`
	Status    string `json:"status"`
	StatusLog string `json:"status_log"`
	Subset    string `json:"subset"`
}

// ActionRequestAccepted defines model for ActionRequestAccepted.
type ActionRequestAccepted struct {
	Uuid string `json:"uuid"`
}

// Disk defines model for Disk.
type Disk struct {
	Dg         string  `json:"dg"`
	Id         string  `json:"id"`
	Model      string  `json:"model"`
	ObjectPath string  `json:"object_path"`
	Region     *string `json:"region,omitempty"`
	Size       int32   `json:"size"`
	Used       int     `json:"used"`
	Vendor     string  `json:"vendor"`
}

// InstanceResourceInfo defines model for InstanceResourceInfo.
type InstanceResourceInfo struct {
	Info []struct {
		Keys []struct {
			Key   string      `json:"key"`
			Value interface{} `json:"value"`
		} `json:"keys"`
		Rid string `json:"rid"`
	} `json:"info"`
	Path     string  `json:"path"`
	Topology *string `json:"topology,omitempty"`
}

// InstanceStatus defines model for InstanceStatus.
type InstanceStatus struct {
	Data map[string]interface{} `json:"data"`
	Path string                 `json:"path"`

	// Version the opensvc client data version
	Version string `json:"version"`
}

// NodeDisks defines model for NodeDisks.
type NodeDisks struct {
	Data *[]Disk `json:"data,omitempty"`
}

// ObjectConfig defines model for ObjectConfig.
type ObjectConfig struct {
	App                    *string   `json:"app,omitempty"`
	Comment                *string   `json:"comment,omitempty"`
	DrpNode                *string   `json:"drp_node,omitempty"`
	DrpNodes               *[]string `json:"drp_nodes,omitempty"`
	Env                    *string   `json:"env,omitempty"`
	FlexMax                *int      `json:"flex_max,omitempty"`
	FlexMin                *int      `json:"flex_min,omitempty"`
	FlexTarget             *int      `json:"flex_target,omitempty"`
	MonitoredResourceCount *int      `json:"monitored_resource_count,omitempty"`
	Orchestrate            *string   `json:"orchestrate,omitempty"`
	Path                   string    `json:"path"`
	RawConfig              *[]byte   `json:"raw_config,omitempty"`
	Scope                  *[]string `json:"scope,omitempty"`
	Topology               *string   `json:"topology,omitempty"`
}

// PostChecks defines model for PostChecks.
type PostChecks struct {
	Vals [][]interface{} `json:"vals"`
	Vars []string        `json:"vars"`
}

// PostDaemonPing defines model for PostDaemonPing.
type PostDaemonPing struct {
	// Nodes list of cluster node
	Nodes []string `json:"nodes"`

	// Objects list of cluster object names
	Objects []string `json:"objects"`

	// Version the opensvc client data version
	Version string `json:"version"`
}

// PostDaemonStatus defines model for PostDaemonStatus.
type PostDaemonStatus struct {
	Changes           []string               `json:"changes"`
	Data              map[string]interface{} `json:"data"`
	PreviousUpdatedAt *time.Time             `json:"previous_updated_at,omitempty"`
	UpdatedAt         *time.Time             `json:"updated_at,omitempty"`

	// Version the opensvc client data version
	Version string `json:"version"`
}

// Problem defines model for Problem.
type Problem struct {
	// Text A human-readable explanation specific to this occurrence of the
	// problem.
	Text string `json:"text"`
}

// QueuedAction defines model for QueuedAction.
type QueuedAction struct {
	Command    string    `json:"command"`
	DequeuedAt time.Time `json:"dequeued_at"`
	Id         int       `json:"id"`
	Nodename   string    `json:"nodename"`
	QueuedAt   time.Time `json:"queued_at"`
	Status     string    `json:"status"`
	SvcId      string    `json:"svc_id"`
	Svcname    string    `json:"svcname"`
}

// QueuedActionDone the action queued result processed by the node
type QueuedActionDone struct {
	DequeuedAt time.Time `json:"dequeued_at"`
	Id         int       `json:"id"`
	Ret        int       `json:"ret"`
	Stderr     string    `json:"stderr"`
	Stdout     string    `json:"stdout"`
}

// QueuedActionRunning defines model for QueuedActionRunning.
type QueuedActionRunning struct {
	// Ids list of queued action ids
	Ids []int `json:"ids"`
}

// QueuedActions defines model for QueuedActions.
type QueuedActions struct {
	Actions []QueuedAction `json:"actions"`
}

// SysReport defines model for SysReport.
type SysReport struct {
	Deleted []string           `json:"deleted"`
	File    openapi_types.File `json:"file"`
}

// Package defines model for package.
type Package struct {
	Arch        string     `json:"arch"`
	InstalledAt *time.Time `json:"installed_at,omitempty"`
	Name        string     `json:"name"`
	Sig         string     `json:"sig"`
	Type        string     `json:"type"`
	Version     string     `json:"version"`
}

// System defines model for system.
type System struct {
	Package *[]Package `json:"package,omitempty"`
}

// Version defines model for version.
type Version struct {
	Version string `json:"version"`
}

// InQuerySync defines model for inQuerySync.
type InQuerySync = bool

// N400 defines model for 400.
type N400 = Problem

// N401 defines model for 401.
type N401 = Problem

// N403 defines model for 403.
type N403 = Problem

// N500 defines model for 500.
type N500 = Problem

// DaemonPingAccepted defines model for DaemonPingAccepted.
type DaemonPingAccepted struct {
	// NodeWithActionQueued list of cluster nodes with pending queued actions
	NodeWithActionQueued *[]string `json:"node_with_action_queued,omitempty"`

	// ObjectWithoutConfig list of object names that requires POST /api/object/config
	ObjectWithoutConfig *[]string `json:"object_without_config,omitempty"`
}

// DaemonStatusAccepted defines model for DaemonStatusAccepted.
type DaemonStatusAccepted struct {
	// NodeWithActionQueued list of cluster nodes with pending queued actions
	NodeWithActionQueued *[]string `json:"node_with_action_queued,omitempty"`

	// ObjectWithoutConfig list of object names that requires POST /api/object/config
	ObjectWithoutConfig *[]string `json:"object_without_config,omitempty"`
}

// basicAuthContextKey is the context key for basicAuth security scheme
type basicAuthContextKey string

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// PostInstanceStatusParams defines parameters for PostInstanceStatus.
type PostInstanceStatusParams struct {
	Sync *InQuerySync `form:"sync,omitempty" json:"sync,omitempty"`
}

// PostChecksJSONRequestBody defines body for PostChecks for application/json ContentType.
type PostChecksJSONRequestBody = PostChecks

// PostDaemonPingJSONRequestBody defines body for PostDaemonPing for application/json ContentType.
type PostDaemonPingJSONRequestBody = PostDaemonPing

// PostDaemonStatusJSONRequestBody defines body for PostDaemonStatus for application/json ContentType.
type PostDaemonStatusJSONRequestBody = PostDaemonStatus

// PostInstanceActionJSONRequestBody defines body for PostInstanceAction for application/json ContentType.
type PostInstanceActionJSONRequestBody = Action

// PutInstanceActionEndJSONRequestBody defines body for PutInstanceActionEnd for application/json ContentType.
type PutInstanceActionEndJSONRequestBody = Action

// PostInstanceResourceInfoJSONRequestBody defines body for PostInstanceResourceInfo for application/json ContentType.
type PostInstanceResourceInfoJSONRequestBody = InstanceResourceInfo

// PostInstanceStatusJSONRequestBody defines body for PostInstanceStatus for application/json ContentType.
type PostInstanceStatusJSONRequestBody = InstanceStatus

// PostNodeActionQueuedDoneJSONRequestBody defines body for PostNodeActionQueuedDone for application/json ContentType.
type PostNodeActionQueuedDoneJSONRequestBody = QueuedActionDone

// PostNodeActionQueuedRunningJSONRequestBody defines body for PostNodeActionQueuedRunning for application/json ContentType.
type PostNodeActionQueuedRunningJSONRequestBody = QueuedActionRunning

// PostNodeDiskJSONRequestBody defines body for PostNodeDisk for application/json ContentType.
type PostNodeDiskJSONRequestBody = NodeDisks

// PostNodeSysReportMultipartRequestBody defines body for PostNodeSysReport for multipart/form-data ContentType.
type PostNodeSysReportMultipartRequestBody = SysReport

// PostSystemJSONRequestBody defines body for PostSystem for application/json ContentType.
type PostSystemJSONRequestBody = System

// PostObjectConfigJSONRequestBody defines body for PostObjectConfig for application/json ContentType.
type PostObjectConfigJSONRequestBody = ObjectConfig
