// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /docs/openapi)
	GetSwagger(ctx echo.Context) error

	// (POST /feed/daemon/ping)
	PostFeedDaemonPing(ctx echo.Context) error

	// (POST /feed/daemon/status)
	PostFeedDaemonStatus(ctx echo.Context) error

	// (POST /feed/instance/action)
	PostFeedInstanceAction(ctx echo.Context) error

	// (PUT /feed/instance/action)
	PutFeedInstanceActionEnd(ctx echo.Context) error

	// (POST /feed/instance/resource_info)
	PostFeedInstanceResourceInfo(ctx echo.Context) error

	// (POST /feed/instance/status)
	PostFeedInstanceStatus(ctx echo.Context, params PostFeedInstanceStatusParams) error

	// (POST /feed/node/disk)
	PostFeedNodeDisk(ctx echo.Context) error

	// (POST /feed/node/system)
	PostFeedSystem(ctx echo.Context) error

	// (POST /feed/object/config)
	PostFeedObjectConfig(ctx echo.Context) error

	// (DELETE /nodes/{node_id}/compliance/modulesets/{mset_id})
	DeleteNodeComplianceModuleset(ctx echo.Context, nodeId string, msetId string) error

	// (POST /nodes/{node_id}/compliance/modulesets/{mset_id})
	PostNodeComplianceModuleset(ctx echo.Context, nodeId string, msetId string) error

	// (DELETE /nodes/{node_id}/compliance/rulesets/{rset_id})
	DeleteNodeComplianceRuleset(ctx echo.Context, nodeId string, rsetId string) error

	// (POST /nodes/{node_id}/compliance/rulesets/{rset_id})
	PostNodeComplianceRuleset(ctx echo.Context, nodeId string, rsetId string) error

	// (GET /version)
	GetVersion(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetSwagger converts echo context to params.
func (w *ServerInterfaceWrapper) GetSwagger(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetSwagger(ctx)
	return err
}

// PostFeedDaemonPing converts echo context to params.
func (w *ServerInterfaceWrapper) PostFeedDaemonPing(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostFeedDaemonPing(ctx)
	return err
}

// PostFeedDaemonStatus converts echo context to params.
func (w *ServerInterfaceWrapper) PostFeedDaemonStatus(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostFeedDaemonStatus(ctx)
	return err
}

// PostFeedInstanceAction converts echo context to params.
func (w *ServerInterfaceWrapper) PostFeedInstanceAction(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostFeedInstanceAction(ctx)
	return err
}

// PutFeedInstanceActionEnd converts echo context to params.
func (w *ServerInterfaceWrapper) PutFeedInstanceActionEnd(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PutFeedInstanceActionEnd(ctx)
	return err
}

// PostFeedInstanceResourceInfo converts echo context to params.
func (w *ServerInterfaceWrapper) PostFeedInstanceResourceInfo(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostFeedInstanceResourceInfo(ctx)
	return err
}

// PostFeedInstanceStatus converts echo context to params.
func (w *ServerInterfaceWrapper) PostFeedInstanceStatus(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params PostFeedInstanceStatusParams
	// ------------- Optional query parameter "sync" -------------

	err = runtime.BindQueryParameter("form", true, false, "sync", ctx.QueryParams(), &params.Sync)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter sync: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostFeedInstanceStatus(ctx, params)
	return err
}

// PostFeedNodeDisk converts echo context to params.
func (w *ServerInterfaceWrapper) PostFeedNodeDisk(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostFeedNodeDisk(ctx)
	return err
}

// PostFeedSystem converts echo context to params.
func (w *ServerInterfaceWrapper) PostFeedSystem(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostFeedSystem(ctx)
	return err
}

// PostFeedObjectConfig converts echo context to params.
func (w *ServerInterfaceWrapper) PostFeedObjectConfig(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostFeedObjectConfig(ctx)
	return err
}

// DeleteNodeComplianceModuleset converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteNodeComplianceModuleset(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "node_id" -------------
	var nodeId string

	err = runtime.BindStyledParameterWithOptions("simple", "node_id", ctx.Param("node_id"), &nodeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter node_id: %s", err))
	}

	// ------------- Path parameter "mset_id" -------------
	var msetId string

	err = runtime.BindStyledParameterWithOptions("simple", "mset_id", ctx.Param("mset_id"), &msetId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter mset_id: %s", err))
	}

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteNodeComplianceModuleset(ctx, nodeId, msetId)
	return err
}

// PostNodeComplianceModuleset converts echo context to params.
func (w *ServerInterfaceWrapper) PostNodeComplianceModuleset(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "node_id" -------------
	var nodeId string

	err = runtime.BindStyledParameterWithOptions("simple", "node_id", ctx.Param("node_id"), &nodeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter node_id: %s", err))
	}

	// ------------- Path parameter "mset_id" -------------
	var msetId string

	err = runtime.BindStyledParameterWithOptions("simple", "mset_id", ctx.Param("mset_id"), &msetId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter mset_id: %s", err))
	}

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostNodeComplianceModuleset(ctx, nodeId, msetId)
	return err
}

// DeleteNodeComplianceRuleset converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteNodeComplianceRuleset(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "node_id" -------------
	var nodeId string

	err = runtime.BindStyledParameterWithOptions("simple", "node_id", ctx.Param("node_id"), &nodeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter node_id: %s", err))
	}

	// ------------- Path parameter "rset_id" -------------
	var rsetId string

	err = runtime.BindStyledParameterWithOptions("simple", "rset_id", ctx.Param("rset_id"), &rsetId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter rset_id: %s", err))
	}

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteNodeComplianceRuleset(ctx, nodeId, rsetId)
	return err
}

// PostNodeComplianceRuleset converts echo context to params.
func (w *ServerInterfaceWrapper) PostNodeComplianceRuleset(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "node_id" -------------
	var nodeId string

	err = runtime.BindStyledParameterWithOptions("simple", "node_id", ctx.Param("node_id"), &nodeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter node_id: %s", err))
	}

	// ------------- Path parameter "rset_id" -------------
	var rsetId string

	err = runtime.BindStyledParameterWithOptions("simple", "rset_id", ctx.Param("rset_id"), &rsetId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter rset_id: %s", err))
	}

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostNodeComplianceRuleset(ctx, nodeId, rsetId)
	return err
}

// GetVersion converts echo context to params.
func (w *ServerInterfaceWrapper) GetVersion(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetVersion(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/docs/openapi", wrapper.GetSwagger)
	router.POST(baseURL+"/feed/daemon/ping", wrapper.PostFeedDaemonPing)
	router.POST(baseURL+"/feed/daemon/status", wrapper.PostFeedDaemonStatus)
	router.POST(baseURL+"/feed/instance/action", wrapper.PostFeedInstanceAction)
	router.PUT(baseURL+"/feed/instance/action", wrapper.PutFeedInstanceActionEnd)
	router.POST(baseURL+"/feed/instance/resource_info", wrapper.PostFeedInstanceResourceInfo)
	router.POST(baseURL+"/feed/instance/status", wrapper.PostFeedInstanceStatus)
	router.POST(baseURL+"/feed/node/disk", wrapper.PostFeedNodeDisk)
	router.POST(baseURL+"/feed/node/system", wrapper.PostFeedSystem)
	router.POST(baseURL+"/feed/object/config", wrapper.PostFeedObjectConfig)
	router.DELETE(baseURL+"/nodes/:node_id/compliance/modulesets/:mset_id", wrapper.DeleteNodeComplianceModuleset)
	router.POST(baseURL+"/nodes/:node_id/compliance/modulesets/:mset_id", wrapper.PostNodeComplianceModuleset)
	router.DELETE(baseURL+"/nodes/:node_id/compliance/rulesets/:rset_id", wrapper.DeleteNodeComplianceRuleset)
	router.POST(baseURL+"/nodes/:node_id/compliance/rulesets/:rset_id", wrapper.PostNodeComplianceRuleset)
	router.GET(baseURL+"/version", wrapper.GetVersion)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xaW3PbuhH+Kxi0D8kMjyRbaTtVn5w46XEvSWo57YPj0UDgisIJCTAAqETx6L93cOFN",
	"BCVZsTI5kzzZIkDs7dsPiwXvMRVZLjhwrfDkHudEkgw0SPuL8f8UINfTNafuJ57gj+YJjjAnGeAJVmYs",
	"woouISNmkl7n5vlciBQIx5vNJsISVC64Arvos9HI/KGCa+Da/EvyPGWUaCb48DcluHlWL/hHCQs8wX8Y",
	"1poO3agavpVinkLmpMSgqGS5WQZP8HMSo2v4WIDSeBPhZ6OzbyH1HSeFXgrJvkDsxI6/hdhXQs5ZHAM3",
	"Mv/0bRx8xTVITlI0BbkCiV5KKaSR/wogviSQCf6W8eSCUsg1xA9SKZciB6mZQ4yY/wZUzz4xvRSFnlHB",
	"FywxA22FUqY0EgvkpiMDUIX0kmgk4WPBJCj09s30Bg0FHQ8XAPHQzRz6BSPMNGSqu3BjQRyVAFdaMp4Y",
	"e/0DIiVZ4039wL0Wcl1svYOUJrpQSLMMlCZZrtAnlqZoDkjCQoJaQowWQiIuYmg7dmrf/Onafa7d5c9N",
	"yVpWrQvqFth2EKmed5QjMllZWixN26N+hOeQMN51gn2MnKQaDYhxdP3qxXg8/utrwoXRPCM65CUqWxpW",
	"1Bth4HFXHPD4K4TlRC+DxipQigk+KwoWhyfYmOwYmqUiCQ73LrkCqXx42jbqJSCRA1crimjKgGsUE01Q",
	"+ULHMLtLWSjHeHLrrIzK6NeCyhh6p29Z7THhFXbuLxdJRbJgqUG598NdB82RR6Hftprp3QZljz+2bLCz",
	"QlIumfrQXTQO+77H85mIIQ2OeErpxYmEpC+jFPsCZsCjb4IZ1+PzOliMa0jAbjKFgqZijZEV8FjI/e6x",
	"EWoq6+X7tauFSlsj46GQO6+40oRTuAYlCknhii9E173MP63Yoj38AdZq93A4AUhawH5bzevl5JAJ20Ql",
	"D8GXtB60ih+yZi8gtMhFKpL1fok+TNaVuyIxrZhmC+JEN2vU+sVe3U5NMFajWkzIqNciBpOxO+ypQLOr",
	"lLNZf8CeGuE39r8XVS2wtSPmedBVVGSZr0A6Y7HMZ3bX3TWoHraZAl8F5y1S+DzLyOcwO7hRxneMaiIT",
	"0OEJmeBMCwnxTPpsn1FR8J7ZQtIlKC2JDlvez5HkU6MWq+hwvtbBMklRkcPDvPfApAsB861Qul3rd8FS",
	"xTVcT9K0UBp8RdZbJDZnHVgqlsx+gOxmTftIheoJecM5tDZvN3e0Q9RHi3RJeLKVfkHrhUTMU+whTuin",
	"WwkrJgo1K/KYaIhnRLdwbh7+YmrTkJRj3jlZODx/lx7cEw1/mO7yOGjC0q52F2hZZIT/IoHEZJ4Cgs95",
	"Srg92iGVA2ULRpEWSC+ZQoLSQkrgFAy89RLe89xJHLznQdqo8NAWe7ME9OvNzdvyFEVN3j25vX714i/n",
	"47O7CE3BHR/+/BQlwMHwW4zmaydTSGaOM8p1Bcx5K6wdCinXIE/NdAohn6ilkDrado0qsozI9dbiyKw7",
	"QOhKo+mvb9796/I9f/3mBrl4oYUUWVMxLfrVjBB8NvX4e25MyguZCwXKTEoFJSn74qLyBAbJIEKFYjwx",
	"r5rifwXIH8/fcw6J0MzO/RtSACjg1vHg2dNgyLbB52BTBbL0WQh7OaEfSAKB7VzS8B5kMz1NH5hpri0Y",
	"rO2THRvT7tJrDyU6Tq5T1prkV3aCQx5Ra6VDydjw1EF1VTn/oNKqYVRbamMAPpMsN9DHo8FocLYXBv2U",
	"Y0/ltJBMr6dGWydqThSjF4UrPawVtmtgntayllrnrmVBJMhytvv1qkTCP/53U/Z+7RJ2dHuNzSaqDj8+",
	"p3FFuSJNgWohEclZI4YTfGZMP7MbeQ7cjE7weDAajLArm6wlw1hQNawm3GNftxnH2hS7ivEE/x309BNJ",
	"EqtaqxV9/sBO6d7u05t/NnrNIdBU4odmUt0g3jd33Gjs7p5rJlnokUTZ8q2Yp4ziO/PMteZci2yYlwWb",
	"ULpLs9euY1ZVSX0tS0tTbX8H6kIHWFD6uYjXj9ec7gratJNDywI2naCf7/diTw97E+Hz0bOutzKmLOG3",
	"vVT2GiPfHPWO96NMoUrRZqbiyW0rR2/vNtF9Kw9v7zZ3dYBJYhzZjW+9ux8R4b1hnZZbzukD60U9fmi3",
	"uug2G0eHZOPou8nyRwNNWdcP64Z3GDbPXbO66lcbkBOUsBXw8ihl+HkHgMouzUXZXD0FhPzih4PmEaVu",
	"928DG4V3Xtn5/4ERGOG8CMDsJY+PA1kRwNhL24f/LmAWhIG7kflJQw0aqtprZekYZqN3thmAhERUgvmv",
	"XACVCyCzwAFs1OrenwYsQVHHQidsqCnMDaI6F58nCtO+ImOqhaw7LOeDszpAvgyKiSaDA+JTFRzNT1Ru",
	"ww6vpwybn7AYk04Z14cUKqMdEfWeUbbRjFRBKSi1KNJ0jZ6oNadLKbgo1FNXjp7vX6m+/i5ZBj0h2yv9",
	"uKRjavRhXF6KHsYzthdt3lHINeoLh90dSC4vck7ELvU90bGU0mfTqdnE+r/RjglGwHgRuUlGRypWINc7",
	"vD11653G117ZYx1dmkE02fPJz4+blO0PiA5PTF8eHpqUrbvO04ClJeKrt/tvlZn2oml4b/7MWLyxhqXM",
	"bvqZiIsUFGg1vM8UaDPuNE5BB1r2l6AJXSKCqhdd551YmAeCc2kXMoT2opL67/LdbgnQvb24uiy795bT",
	"rLRPS0aXSAsUO3XMaNZY1H7d6q/l/cet3ni8HbHA9651b3a3PrULKk3Csr1jHyT7roOkQK+qcmS7snC6",
	"lOePwHsmHCbPagu40GghCh43WKLnG1F/GwTuG9GvgGjVMXZHxyAnXOgO3rToR5uhgiOxZn1ydXlC9NTR",
	"6hNzNFCOY7pAD/wIOqvNIrqJux9kt2uieA/Zyopq5UOoVh5NtNePT7PyG5OsPIxi5ako9vqrCFb+XuhV",
	"HkWu198LtV7vIVb5eyTW65+0WtNq41Ld3wy3nSVBF5IjkrPGBz+dy+P/VkNfdXm864hQSu+9Uj7q6peS",
	"nMxZyuw3Bncb51lDFC7fCpniCR4KOsabu83/AwAA///HqmURCjYAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
