// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /docs/openapi)
	GetSwagger(ctx echo.Context) error

	// (POST /feed/daemon/ping)
	PostFeedDaemonPing(ctx echo.Context) error

	// (POST /feed/daemon/status)
	PostFeedDaemonStatus(ctx echo.Context) error

	// (POST /feed/instance/action)
	PostFeedInstanceAction(ctx echo.Context) error

	// (PUT /feed/instance/action)
	PutFeedInstanceActionEnd(ctx echo.Context) error

	// (POST /feed/instance/resource_info)
	PostFeedInstanceResourceInfo(ctx echo.Context) error

	// (POST /feed/instance/status)
	PostFeedInstanceStatus(ctx echo.Context, params PostFeedInstanceStatusParams) error

	// (POST /feed/node/disk)
	PostFeedNodeDisk(ctx echo.Context) error

	// (POST /feed/node/system)
	PostFeedSystem(ctx echo.Context) error

	// (POST /feed/object/config)
	PostFeedObjectConfig(ctx echo.Context) error

	// (DELETE /nodes/{node_id}/compliance/modulesets/{mset_id})
	DeleteNodeComplianceModuleset(ctx echo.Context, nodeId InPathNodeId, msetId InPathMsetId) error

	// (POST /nodes/{node_id}/compliance/modulesets/{mset_id})
	PostNodeComplianceModuleset(ctx echo.Context, nodeId InPathNodeId, msetId InPathMsetId) error

	// (DELETE /nodes/{node_id}/compliance/rulesets/{rset_id})
	DeleteNodeComplianceRuleset(ctx echo.Context, nodeId InPathNodeId, rsetId InPathRsetId) error

	// (POST /nodes/{node_id}/compliance/rulesets/{rset_id})
	PostNodeComplianceRuleset(ctx echo.Context, nodeId InPathNodeId, rsetId InPathRsetId) error

	// (GET /version)
	GetVersion(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetSwagger converts echo context to params.
func (w *ServerInterfaceWrapper) GetSwagger(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetSwagger(ctx)
	return err
}

// PostFeedDaemonPing converts echo context to params.
func (w *ServerInterfaceWrapper) PostFeedDaemonPing(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostFeedDaemonPing(ctx)
	return err
}

// PostFeedDaemonStatus converts echo context to params.
func (w *ServerInterfaceWrapper) PostFeedDaemonStatus(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostFeedDaemonStatus(ctx)
	return err
}

// PostFeedInstanceAction converts echo context to params.
func (w *ServerInterfaceWrapper) PostFeedInstanceAction(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostFeedInstanceAction(ctx)
	return err
}

// PutFeedInstanceActionEnd converts echo context to params.
func (w *ServerInterfaceWrapper) PutFeedInstanceActionEnd(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PutFeedInstanceActionEnd(ctx)
	return err
}

// PostFeedInstanceResourceInfo converts echo context to params.
func (w *ServerInterfaceWrapper) PostFeedInstanceResourceInfo(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostFeedInstanceResourceInfo(ctx)
	return err
}

// PostFeedInstanceStatus converts echo context to params.
func (w *ServerInterfaceWrapper) PostFeedInstanceStatus(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params PostFeedInstanceStatusParams
	// ------------- Optional query parameter "sync" -------------

	err = runtime.BindQueryParameter("form", true, false, "sync", ctx.QueryParams(), &params.Sync)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter sync: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostFeedInstanceStatus(ctx, params)
	return err
}

// PostFeedNodeDisk converts echo context to params.
func (w *ServerInterfaceWrapper) PostFeedNodeDisk(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostFeedNodeDisk(ctx)
	return err
}

// PostFeedSystem converts echo context to params.
func (w *ServerInterfaceWrapper) PostFeedSystem(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostFeedSystem(ctx)
	return err
}

// PostFeedObjectConfig converts echo context to params.
func (w *ServerInterfaceWrapper) PostFeedObjectConfig(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostFeedObjectConfig(ctx)
	return err
}

// DeleteNodeComplianceModuleset converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteNodeComplianceModuleset(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "node_id" -------------
	var nodeId InPathNodeId

	err = runtime.BindStyledParameterWithOptions("simple", "node_id", ctx.Param("node_id"), &nodeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter node_id: %s", err))
	}

	// ------------- Path parameter "mset_id" -------------
	var msetId InPathMsetId

	err = runtime.BindStyledParameterWithOptions("simple", "mset_id", ctx.Param("mset_id"), &msetId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter mset_id: %s", err))
	}

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteNodeComplianceModuleset(ctx, nodeId, msetId)
	return err
}

// PostNodeComplianceModuleset converts echo context to params.
func (w *ServerInterfaceWrapper) PostNodeComplianceModuleset(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "node_id" -------------
	var nodeId InPathNodeId

	err = runtime.BindStyledParameterWithOptions("simple", "node_id", ctx.Param("node_id"), &nodeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter node_id: %s", err))
	}

	// ------------- Path parameter "mset_id" -------------
	var msetId InPathMsetId

	err = runtime.BindStyledParameterWithOptions("simple", "mset_id", ctx.Param("mset_id"), &msetId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter mset_id: %s", err))
	}

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostNodeComplianceModuleset(ctx, nodeId, msetId)
	return err
}

// DeleteNodeComplianceRuleset converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteNodeComplianceRuleset(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "node_id" -------------
	var nodeId InPathNodeId

	err = runtime.BindStyledParameterWithOptions("simple", "node_id", ctx.Param("node_id"), &nodeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter node_id: %s", err))
	}

	// ------------- Path parameter "rset_id" -------------
	var rsetId InPathRsetId

	err = runtime.BindStyledParameterWithOptions("simple", "rset_id", ctx.Param("rset_id"), &rsetId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter rset_id: %s", err))
	}

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteNodeComplianceRuleset(ctx, nodeId, rsetId)
	return err
}

// PostNodeComplianceRuleset converts echo context to params.
func (w *ServerInterfaceWrapper) PostNodeComplianceRuleset(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "node_id" -------------
	var nodeId InPathNodeId

	err = runtime.BindStyledParameterWithOptions("simple", "node_id", ctx.Param("node_id"), &nodeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter node_id: %s", err))
	}

	// ------------- Path parameter "rset_id" -------------
	var rsetId InPathRsetId

	err = runtime.BindStyledParameterWithOptions("simple", "rset_id", ctx.Param("rset_id"), &rsetId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter rset_id: %s", err))
	}

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostNodeComplianceRuleset(ctx, nodeId, rsetId)
	return err
}

// GetVersion converts echo context to params.
func (w *ServerInterfaceWrapper) GetVersion(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetVersion(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/docs/openapi", wrapper.GetSwagger)
	router.POST(baseURL+"/feed/daemon/ping", wrapper.PostFeedDaemonPing)
	router.POST(baseURL+"/feed/daemon/status", wrapper.PostFeedDaemonStatus)
	router.POST(baseURL+"/feed/instance/action", wrapper.PostFeedInstanceAction)
	router.PUT(baseURL+"/feed/instance/action", wrapper.PutFeedInstanceActionEnd)
	router.POST(baseURL+"/feed/instance/resource_info", wrapper.PostFeedInstanceResourceInfo)
	router.POST(baseURL+"/feed/instance/status", wrapper.PostFeedInstanceStatus)
	router.POST(baseURL+"/feed/node/disk", wrapper.PostFeedNodeDisk)
	router.POST(baseURL+"/feed/node/system", wrapper.PostFeedSystem)
	router.POST(baseURL+"/feed/object/config", wrapper.PostFeedObjectConfig)
	router.DELETE(baseURL+"/nodes/:node_id/compliance/modulesets/:mset_id", wrapper.DeleteNodeComplianceModuleset)
	router.POST(baseURL+"/nodes/:node_id/compliance/modulesets/:mset_id", wrapper.PostNodeComplianceModuleset)
	router.DELETE(baseURL+"/nodes/:node_id/compliance/rulesets/:rset_id", wrapper.DeleteNodeComplianceRuleset)
	router.POST(baseURL+"/nodes/:node_id/compliance/rulesets/:rset_id", wrapper.PostNodeComplianceRuleset)
	router.GET(baseURL+"/version", wrapper.GetVersion)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xaW3PbuhH+Kxi0DzkzPJJspe1UfXLipMdtT+JKTvvgeDQQuKJwQgIMACpWPPrvHVx4",
	"k6CrLZ90kidbBLiL/Xb3w3KBB0xFlgsOXCs8eMA5kSQDDdL+Yvya6NmvCvRVbH7HoKhkuWaC4wG+ukRi",
	"ivQMUCbiIgUFGkeYmaGc6BmOMCcZ4AHOFOgxi3GEJXwumIQYD7QsIMKKziAjRrRe5Gaq0pLxBC+XkVf+",
	"TsSwXTkXMYT1mpFj9Q53Gi23mSyPNPnfBcjFaMGpgx8P8GfzpBaszFhAykSIFAjHSyNHgsoFV2Cd+LLX",
	"M3+o4Bq4Nv+SPE8ZJcai7m/KmPXQEPhHCVM8wH/o1pHRdaOqey3FJIXMaWkD84rEaAifC1AaLyP8snf2",
	"HFo/cFLomZDsK8RObf851L4VcsLiGLjR+afnAfiKa5CcpGgEcg4SvZFSSKP/LUB8SSAT/Jrx5IJSyDXE",
	"By0plyIHqZmLGDH5Dagef2F6Jgo9poJPWbKeCilT2iSDm45MgCqkZ0QjH/MKXb8f3aCuoP3uFCDuupld",
	"LzDCTEOm1gU3BOJoNU2qB0RKsrBp4x+410LQxRYdpDTRhUKaZaA0yXKFvrA0RRNAEqYS1AxiNBXSMUoL",
	"2JF98we0u6DdhueyZC27rAvqBKwCRKrna4sjMplbWixN27H8CE8gYXwdBPsYOU11NCDG0fDt636//9d3",
	"hAuz8ozoEEpUtlZYUW+EgQe2DODxI5TZfSVkrAKlmODjomBxeIL1yZahcSqS4PBGkXOQyrunbaPZEEUO",
	"XM0poikDrlFMNEHlC1Fgt6t3xtty9/TerxWVPvSgr1jtY8Iv2MFfCklFMmWpiXKPw91aNEc+Cv221Uzv",
	"dlBuwGPFBjsrpOWSqU/rQuMw9huQz0QMaXDEU8rGOJGQbMooxb6CGfDRN8CM6/557SzGNSRgN5lCQXNh",
	"jZE58FjI3fBYDzUX6/V72ZWg0tbIIBSC84orTTiFIShRSApXfCrW4WX+acUW7eFPsFDbh8MJQNICdttq",
	"Xi8nh0xYJSq5T3xJi6Bd+D4yNwaEFrlIRbLYrdG7yUK5zROjimlWQpzoZo1av7hxbacmGLuiWk3IKPPF",
	"YTJ2iz1V0Gwr5WzW77GnRvi9/e91VQus7Ih5HoSKiizzFcjaWCzzsd11tw2qwzZT4PPgvGkK9+OM3IfZ",
	"wY0yvmVUE5mADk/IBGdaSIjH0mf7mIqCb5gtJJ2B0pLosOWbOZJ8adRiFR1OFjpYJikqcjgMvQOTLhSY",
	"10Lpdq2/HiyVX8P1JE0LpUFW38zhIrE5a89SsWT2PXQ3a9onKlRPyBsO0Nq87dzRdtEmWqQzwpOV9Ata",
	"LyRinmL3AWEz3UqYM1GocZHHREM8JroV5+bhz6Y2DWk55p2TucPzd4ngDm/4j+l1HgdNWLq+ugs0KzLC",
	"f5ZAYjJJAcF9nhJuP+2QyoGyKaNIC6RnTCFBaSElcAq+JfSR505j5yMP0kYVD221NzNAv9zcXJdfUdTk",
	"3Yvb4dvXfznvn91FaATu8+HPP6EEOBh+i9Fk4XQKycznjHJdAfO9FV4dCi2uQZ6a6RRCmKiZkDpahUYV",
	"WUbkYkU4MnI7CF1pNPrl/Yd/XX7k797fIOcvNJUiay5Mi83LjBDcm3r8Izcm5YXMhQJlJqWCkpR9dV55",
	"AZ2kE6FCMZ6YV03xPwfkP88/cg6J0MzO/RtSACgAa7/z8qegy1aDz4VN5cgSs1Ds5YR+IgkEtnNJw3uQ",
	"zfQ0PTDTXFswWNsnWzam7aXXDkp0nFynrDXJS3aKQ4iohdKhZGwgtVddVc7fq7RqGNXW2hiAe5LlJvRx",
	"r9PrnO0Mg82UY7/KaSGZXozMap2qCVGMXhSu9LBW2K6BeVrrmmmdu5YFkSDL2e7X2zIS/vHfm7L3a0XY",
	"0VUZrpHsPn58TuOKckWaAtVCIpKzhg8H+MyYfmY38hy4GR3gfqfX6WFXNllLurGgqltNeMC+bjPA2hS7",
	"ivEA/x306AtJEru0Viv6/MBO6c7u0/t/NnrNoaCp1HfNpLpBvGtuv9HY3T7XTLKhRxJly7dikjKK78wz",
	"15pzLbJuXhZsQul1mh26jllVJW1qWVqaauMdqAtdwILSr0S8eLrm9LqiZTs5tCxgueb0890obuhhLyN8",
	"3nu5jlbGlCX8NkplrzHyzVEPvB9lClULbWYqHty2cvT2bhk9tPLw9m55VzuYJAbIdf/Wu/sRHt7p1lG5",
	"5ZzesV7V07t2pYtus7G3Tzb2vpksf7KgKev6bt3wDofNK9esrvrVJsgJStgcePkpZfh5SwCVXZqLsrl6",
	"ihDywvcPmifUutq/DWwUHryy8/8dR2CE8yIQZm94fFyQFYEYe8PjbyXMgmHgTmR+0FCDhqr2Wlk6htno",
	"g20GICERlWD+KwWgUgAyAvZgo1b3/jTBElR1bOiEDTWFuYmotYPPE7lpV5Ex0kLWHZbzzlntIF8GxUST",
	"zh7+qQqO5pWg2zDg9ZRu8wqLMemUfj2kUOlt8ahHRtlGM1IFpaDUtEjTBXqhFpzOpOCiUD+5cvR8t6T6",
	"+LtkGfSCrEr6fknH1OjduDwU3Y9nbC/avKOQa9QXLna3RHJ5kHMidqnPiY6llE02nZpNLP6NdkzQAwZF",
	"5CaZNVIxB7nYgvbIyTsN1n6xxwJdmkE02XHl5/tNyvYFov0T05eH+yZl66zzNMHSUvHo7f65MtMeNHUf",
	"/J3VpTUsZXbTr67Xqu6Dv0u7dCtOQQda9pegCZ0hUt/LdZ13YsM84JxLK8gQ2utK66+NO72HlgCNi7sG",
	"gL3m+1vGrmZoeSfQ/6kW196tY2t4WdMH3jOLMrFbA8OFRlNR8LiReRvuXfoTFnD3Lh/h9qoL6z7Hgnl2",
	"odd8qMVmD5r0+ob8d1xSB9q9R2RuHRtEN8PhOyH2ZnDt4BVZsYo8hFXk0ZwyfNaIHB7CKMNH8Yn8f2ET",
	"eRSX/I5++z2ZZPiDR2oeaRyY+lO/NlgSdCE5IjlrXOZYOxj8TzX0qIPBbeVfqX3jceFRx3qU5GTCUmbP",
	"j++WDlmTwS4RCpniAe4K2sfLu+X/AgAA//8lUKvdVjUAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
